#Requires -Version 7.0
<#
Read-only live fence for each fixed matrix cell. The gate's full raw/profile
collector runs once while the original enabled settings are current. Across the
matrix the only permitted change is the requested PRTG enabled bit/settings
revision; this live fence re-reads the completed job and all 15,000 raw rows and
profile/binding rows and requires all original source, policy, scope, authority,
identity, channel, binding, and proof references to remain exact.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][uri]$BaseUri,
    [Parameter(Mandatory)][uri]$PrtgFixtureUri,
    [Parameter(Mandatory)][Microsoft.PowerShell.Commands.WebRequestSession]$WebSession,
    [Parameter(Mandatory)][string]$ManifestPath,
    [Parameter(Mandatory)][string]$ProofFencePath,
    [Parameter(Mandatory)][string]$JobId,
    [Parameter(Mandatory)][long]$JobVersion,
    [Parameter(Mandatory)][int]$JobWave,
    [Parameter(Mandatory)][bool]$ExpectedPrtgEnabled,
    [ValidateRange(1,3600)][int]$MaxSeconds=600
)
$ErrorActionPreference='Stop'
$addr=$null
foreach($uri in @($BaseUri,$PrtgFixtureUri)){if($uri.Scheme -cnotin @('http','https') -or -not[Net.IPAddress]::TryParse($uri.DnsSafeHost.Trim('[',']'),[ref]$addr) -or -not[Net.IPAddress]::IsLoopback($addr) -or $uri.Port -lt 1 -or $uri.UserInfo -or $uri.Query -or $uri.Fragment){throw 'Live qualification fence requires explicit numeric-loopback URLs.'}}
$base=[uri]($BaseUri.AbsoluteUri.TrimEnd('/')+'/');$manifest=Get-Content -LiteralPath $ManifestPath -Raw|ConvertFrom-Json -Depth 16
$ids=@($manifest.sensorIds|ForEach-Object{[long]$_});$fences=@{};foreach($fence in $manifest.sensorFences){$fences[[long]$fence.sensorObjid]=$fence}
if($ids.Count -ne 15000 -or @($ids|Sort-Object -Unique).Count -ne 15000 -or $fences.Count -ne 15000){throw 'Live fence requires the exact 15,000 selected IDs and one saved fence per sensor.'}
$proofFenceFull=[IO.Path]::GetFullPath($ProofFencePath);$proofFence=$null;$proofById=@{};$proofRows=[Collections.Generic.List[object]]::new()
if(Test-Path -LiteralPath $proofFenceFull -PathType Leaf){$proofFence=Get-Content -LiteralPath $proofFenceFull -Raw|ConvertFrom-Json -Depth 8;if($proofFence.schema -cne 'prtg-matrix-proof-fence-v1' -or $proofFence.jobId -cne $JobId -or $proofFence.sensorCount -ne 15000 -or $proofFence.manifestSha256 -cne (Get-FileHash -LiteralPath $ManifestPath -Algorithm SHA256).Hash -or $proofFence.sensorProofs.Count -ne 15000){throw 'Saved proof fence is stale, incomplete, or belongs to another job/manifest.'};foreach($entry in $proofFence.sensorProofs){$proofById[[long]$entry.sensorObjid]=[string]$entry.qualificationProofReference}}
$handler=[Net.Http.HttpClientHandler]::new();$handler.AllowAutoRedirect=$false;$handler.UseCookies=$true;$handler.CookieContainer=$WebSession.Cookies;$client=[Net.Http.HttpClient]::new($handler);$client.Timeout=[Threading.Timeout]::InfiniteTimeSpan
$deadline=[Threading.CancellationTokenSource]::new([TimeSpan]::FromSeconds($MaxSeconds));$json=[Text.Json.JsonDocumentOptions]::new();$json.MaxDepth=32
function Get-Data([string]$path,[int]$bytes=512KB){$linked=[Threading.CancellationTokenSource]::CreateLinkedTokenSource($deadline.Token);$linked.CancelAfter([TimeSpan]::FromSeconds(30));$request=$null;$response=$null;$stream=$null;$memory=[IO.MemoryStream]::new();try{$request=[Net.Http.HttpRequestMessage]::new([Net.Http.HttpMethod]::Get,[uri]::new($base,$path));$request.Headers.Add('X-Requested-By','LogForesight');$request.Headers.Accept.ParseAdd('application/json');$response=$client.SendAsync($request,[Net.Http.HttpCompletionOption]::ResponseHeadersRead,$linked.Token).GetAwaiter().GetResult();if([int]$response.StatusCode -ge 300 -and [int]$response.StatusCode -lt 400){throw 'Live qualification fence refuses redirects.'};if(-not$response.IsSuccessStatusCode){throw "Live qualification API returned HTTP $([int]$response.StatusCode)."};if($response.Content.Headers.ContentType.MediaType -cne 'application/json' -or $response.Content.Headers.ContentLength -gt $bytes){throw 'Live qualification API response MIME/declared bytes are invalid.'};$stream=$response.Content.ReadAsStreamAsync($linked.Token).GetAwaiter().GetResult();$buffer=[byte[]]::new(8192);while(($read=$stream.ReadAsync($buffer,0,$buffer.Length,$linked.Token).GetAwaiter().GetResult()) -gt 0){if($memory.Length+$read -gt $bytes){throw 'Live qualification response exceeded its streaming byte limit.'};$memory.Write($buffer,0,$read)};$doc=[Text.Json.JsonDocument]::Parse([ReadOnlyMemory[byte]]$memory.ToArray(),$json);try{return $doc.RootElement.Clone()}finally{$doc.Dispose()}}finally{if($stream){$stream.Dispose()};$memory.Dispose();if($response){$response.Dispose()};if($request){$request.Dispose()};$linked.Dispose()}}
function Get-ApiData($document){if($document.ValueKind -ne 'Object'){throw 'Live qualification API envelope must be an object.'};return $document.GetProperty('data')}
function Need([bool]$condition,[string]$reason){if(-not$condition){throw $reason}}
try{
    $settings=Get-ApiData (Get-Data 'api/admin/settings' 128KB);Need ($settings.GetProperty('prtgEnabled').GetBoolean() -eq $ExpectedPrtgEnabled) 'Current PRTG enabled state differs from this fixed matrix condition.';Need ($settings.GetProperty('prtgUrl').GetString().TrimEnd('/') -ceq $PrtgFixtureUri.AbsoluteUri.TrimEnd('/')) 'Current saved PRTG URL differs from the explicit loopback fixture.'
    $contract=Get-ApiData (Get-Data 'api/prtg/monitoring/trusted-sampling/qualification-jobs/contract' 32KB);Need ($contract.GetProperty('settingsRevision').GetString() -ceq $settings.GetProperty('revision').GetString() -and $contract.GetProperty('policyRevision').GetString() -ceq $manifest.policyRevision -and $contract.GetProperty('scopeFingerprint').GetString() -ceq $manifest.scopeFingerprint -and $contract.GetProperty('selectedSensors').GetInt32() -eq 15000 -and $contract.GetProperty('prtgEnabled').GetBoolean() -eq $ExpectedPrtgEnabled -and ($ExpectedPrtgEnabled -or -not $contract.GetProperty('capacityPilotCurrent').GetBoolean())) 'Current qualification contract has source/policy/scope/condition/capacity drift.';if($ExpectedPrtgEnabled){Need $contract.GetProperty('capacityPilotCurrent').GetBoolean() 'Enabled matrix condition requires a current capacity pilot.'}
    $prefix='api/prtg/monitoring/trusted-sampling/';$current=Get-ApiData (Get-Data ($prefix+'qualification-jobs/current') 32KB);Need ($current.GetProperty('jobId').GetString() -ceq $JobId -and $current.GetProperty('version').GetInt64() -eq $JobVersion -and $current.GetProperty('wave').GetInt32() -eq $JobWave -and $current.GetProperty('status').GetString() -ceq 'completed') 'Current durable job differs from the sealed ID/version/wave/status.'
    foreach($field in @('scopeFingerprint','policyRevision','sourceGeneration','settingsRevision','authorityContextFingerprint')){Need ($current.GetProperty($field).GetString() -ceq [string]$manifest.$field) "Completed job $field differs from the original sealed manifest."}
    $rawCount=0;$profileCount=0
    for($offset=0;$offset -lt 15000;$offset+=100){$deadline.Token.ThrowIfCancellationRequested();$raw=Get-ApiData (Get-Data ($prefix+"qualification-jobs/$JobId/page?offset=$offset&limit=100") 128KB);$expected=$ids[$offset..([Math]::Min(14999,$offset+99))];$pageLimit=[Math]::Min(100,15000-$offset);Need ($raw.GetProperty('status').GetString() -ceq 'completed' -and $raw.GetProperty('offset').GetInt32() -eq $offset -and $raw.GetProperty('limit').GetInt32() -eq $pageLimit -and $raw.GetProperty('total').GetInt32() -eq 15000) 'Raw qualification page metadata/status drifted.';$rows=$raw.GetProperty('rows');Need ($rows.ValueKind -eq 'Array' -and $rows.GetArrayLength() -eq $expected.Count) 'Raw qualification page is partial.';$index=0;foreach($row in $rows.EnumerateArray()){$id=$row.GetProperty('sensorObjid').GetInt64();$f=$fences[$id];Need ($id -eq $expected[$index] -and $null -ne $f -and $row.GetProperty('status').GetString() -ceq 'qualified' -and $row.GetProperty('hasQualificationProof').GetBoolean() -and $row.GetProperty('bindingRevision').GetInt64() -eq [long]$f.bindingRevision -and $row.GetProperty('bindingFingerprint').GetString() -ceq [string]$f.bindingFingerprint) 'Current raw proof row or binding differs from the sealed sensor fence.';$index++};$next=$raw.GetProperty('nextOffset');$expectedNext=if($offset+100 -lt 15000){$offset+100}else{$null};Need ((($null -eq $expectedNext) -and $next.ValueKind -eq 'Null') -or ($next.ValueKind -eq 'Number' -and $next.GetInt32() -eq $expectedNext)) 'Raw page continuation metadata is inconsistent.';$rawCount+=$rows.GetArrayLength()
        $profilePage=Get-ApiData (Get-Data ($prefix+"profiles?offset=$offset&limit=100") 512KB);Need ($profilePage.GetProperty('offset').GetInt32() -eq $offset -and $profilePage.GetProperty('limit').GetInt32() -eq $pageLimit -and $profilePage.GetProperty('total').GetInt32() -eq 15000 -and $profilePage.GetProperty('settingsRevision').GetString() -ceq $settings.GetProperty('revision').GetString() -and $profilePage.GetProperty('policyRevision').GetString() -ceq $manifest.policyRevision -and $profilePage.GetProperty('sourceGeneration').GetString() -ceq $manifest.sourceGeneration -and $profilePage.GetProperty('authorityContextFingerprint').GetString() -ceq $manifest.authorityContextFingerprint -and $profilePage.GetProperty('prtgEnabled').GetBoolean() -eq $ExpectedPrtgEnabled) 'Current profile page metadata/source/authority/condition drifted.';$profileNext=$profilePage.GetProperty('nextOffset');$expectedProfileNext=if($offset+100 -lt 15000){$offset+100}else{$null};Need ((($null -eq $expectedProfileNext) -and $profileNext.ValueKind -eq 'Null') -or ($profileNext.ValueKind -eq 'Number' -and $profileNext.GetInt32() -eq $expectedProfileNext)) 'Profile page continuation metadata is inconsistent.';$profiles=$profilePage.GetProperty('rows');Need ($profiles.ValueKind -eq 'Array' -and $profiles.GetArrayLength() -eq $expected.Count) 'Current profile page is partial.';$index=0;foreach($profile in $profiles.EnumerateArray()){$id=$profile.GetProperty('sensorObjid').GetInt64();$f=$fences[$id];$proof=$profile.GetProperty('qualificationProofReference').GetString();Need ($id -eq $expected[$index] -and $profile.GetProperty('currentIdentityEpoch').GetInt64() -eq [long]$f.identityEpoch -and $profile.GetProperty('currentChannelGeneration').GetString() -ceq [string]$f.channelGeneration -and $profile.GetProperty('bindingRevision').GetInt64() -eq [long]$f.bindingRevision -and $profile.GetProperty('bindingFingerprint').GetString() -ceq [string]$f.bindingFingerprint -and $profile.GetProperty('bindingStatus').GetString() -ceq 'qualified' -and -not[string]::IsNullOrWhiteSpace($proof)) 'Current identity, profile binding, or proof reference differs from the sealed fence.';if($proofById.Count -gt 0){Need ($proofById.ContainsKey($id) -and $proofById[$id] -ceq $proof) 'Qualification proof reference changed since the first fixed matrix cell.'}else{$proofRows.Add(@{sensorObjid=$id;qualificationProofReference=$proof})};if($ExpectedPrtgEnabled){Need ($profile.GetProperty('status').GetString() -ceq 'ready') 'Enabled current matrix condition requires every profile to remain ready.'} else {Need ($profile.GetProperty('status').GetString() -in @('ready','source_authority_incomplete','waiting')) 'Disabled baseline profile has an unrecognized current status.'};$index++};$profileCount+=$profiles.GetArrayLength()
    }
    Need ($rawCount -eq 15000 -and $profileCount -eq 15000) 'Live exact coverage row totals do not equal 15,000.'
    $finalSettings=Get-ApiData (Get-Data 'api/admin/settings' 128KB);Need ($finalSettings.GetProperty('revision').GetString() -ceq $settings.GetProperty('revision').GetString() -and $finalSettings.GetProperty('prtgEnabled').GetBoolean() -eq $ExpectedPrtgEnabled -and $finalSettings.GetProperty('prtgUrl').GetString().TrimEnd('/') -ceq $PrtgFixtureUri.AbsoluteUri.TrimEnd('/')) 'Settings/source changed while the exact live pages were read.'
    $finalContract=Get-ApiData (Get-Data 'api/prtg/monitoring/trusted-sampling/qualification-jobs/contract' 32KB)
    $finalCapacity=$finalContract.GetProperty('capacityPilotCurrent').GetBoolean();$finalPolicy=$finalContract.GetProperty('policyRevision').GetString();$finalScope=$finalContract.GetProperty('scopeFingerprint').GetString();$finalSelected=$finalContract.GetProperty('selectedSensors').GetInt32();$finalEnabled=$finalContract.GetProperty('prtgEnabled').GetBoolean();$finalRevision=$finalContract.GetProperty('settingsRevision').GetString()
    Need ($finalRevision -ceq $settings.GetProperty('revision').GetString()) 'Qualification settings revision changed during exact paging.'
    Need ($finalPolicy -ceq $manifest.policyRevision) 'Qualification policy revision changed during exact paging.'
    Need ($finalScope -ceq $manifest.scopeFingerprint) 'Qualification scope changed during exact paging.'
    Need ($finalSelected -eq 15000) 'Qualification selected sensor count changed during exact paging.'
    Need ($finalEnabled -eq $ExpectedPrtgEnabled) 'Qualification enabled state changed during exact paging.'
    Need ((($ExpectedPrtgEnabled -and $finalCapacity) -or ((-not $ExpectedPrtgEnabled) -and (-not $finalCapacity)))) 'Qualification capacity pilot state changed during exact paging.'
    $finalCurrent=Get-ApiData (Get-Data ($prefix+'qualification-jobs/current') 32KB);Need ($finalCurrent.GetProperty('jobId').GetString() -ceq $JobId -and $finalCurrent.GetProperty('version').GetInt64() -eq $JobVersion -and $finalCurrent.GetProperty('wave').GetInt32() -eq $JobWave -and $finalCurrent.GetProperty('status').GetString() -ceq 'completed') 'Qualification job changed during paging.';foreach($field in @('scopeFingerprint','policyRevision','sourceGeneration','settingsRevision','authorityContextFingerprint')){Need ($finalCurrent.GetProperty($field).GetString() -ceq [string]$manifest.$field) "Final qualification job $field changed during paging."}
    if($proofById.Count -eq 0){if($proofRows.Count -ne 15000){throw 'First-cell proof fence is incomplete.'};$proofFenceValue=[ordered]@{schema='prtg-matrix-proof-fence-v1';jobId=$JobId;manifestSha256=(Get-FileHash -LiteralPath $ManifestPath -Algorithm SHA256).Hash;sensorCount=15000;sensorProofs=$proofRows.ToArray()};$tmp=$proofFenceFull+'.tmp';$null=New-Item -ItemType Directory -Path (Split-Path -Parent $proofFenceFull) -Force;[IO.File]::WriteAllText($tmp,($proofFenceValue|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));[IO.File]::Move($tmp,$proofFenceFull,$true)}
    $proofFenceHash=(Get-FileHash -LiteralPath $proofFenceFull -Algorithm SHA256).Hash
    [pscustomobject]@{schema='prtg-live-matrix-qualification-fence-v1';status='current';jobId=$JobId;jobVersion=$JobVersion;jobWave=$JobWave;settingsRevision=$settings.GetProperty('revision').GetString();prtgEnabled=$ExpectedPrtgEnabled;rawRows=$rawCount;profileRows=$profileCount;proofFenceSha256=$proofFenceHash;sourceGeneration=$manifest.sourceGeneration;policyRevision=$manifest.policyRevision;scopeFingerprint=$manifest.scopeFingerprint;authorityContextFingerprint=$manifest.authorityContextFingerprint;nativeSourceVerified=$false;capacityAccepted=$false;retentionAccepted=$false;wholeRoundAccepted=$false}
}finally{$client.Dispose();$deadline.Dispose()}
