namespace LogForesight.Core.Analysis;

/// <summary>
/// 內建規則種子：初次部署時寫入外部儲存（DB blob，key=rules）的起始內容，也是
/// <see cref="KnownIssueCatalog.Rules"/> 在未呼叫 Initialize 前的預設值（單元測試降級路徑）。
/// 這裡不再是唯一的規則來源——使用者可在規則庫停用/新增規則；Web 規則維護頁的「內建規則升級」
/// 用 <see cref="Version"/> 判斷是否有新版種子內容可匯入。Id 一經出貨永不改名（見 docs/RULES-SPEC.md）。
/// </summary>
public static class KnownIssueSeed
{
    /// <summary>種子版本：每次調整 CreateRules() 的內容（新增規則、修訂知識庫文字）就遞增，
    /// Web 規則維護頁的「內建規則升級」依此判斷規則庫是否落後於程式內建的種子。
    /// v2（EventLogReader 遷移）：新增 Microsoft Defender 與 RDP TerminalServices 兩類 Operational
    /// 頻道的規則（見 docs/RULES-SPEC.md 與 README「監控的危險訊號清單」）。
    /// v3（docs/archive/HISTORY.md #1，B1 三級化）：原 Severity=Critical 的 7 條規則改為
    /// High＋ElevatesDayRisk=true，行為不變（仍讓命中當天判定為高風險日），嚴重度顯示收斂為三級。
    /// v4（docs/LINUX-RULES.md）：新增 17 條 Platform="linux" 種子規則（SSH 暴力破解、
    /// 帳號/群組異動、auditd 滅跡、儲存/硬體/OOM、服務失敗迴圈、時間同步、cron 失敗），
    /// pattern 字串為 probe 前的通用草案，日後依真實環境輸出校正時再遞增版本。
    /// v5（C1 規則涵蓋補強）：新增 17 條 Windows 規則（Kerberos 預先驗證 4771、帳號停用/刪除 4725/4726、
    /// 帳號解鎖 4767、帳號屬性變更 4738、排程刪除 4699、排程異動 4700-4702、防火牆變更 4946-4948、
    /// 記錄檔清除 104、電腦帳號異動 4741/4743、網域群組異動 4727/4730/4754/4758、網域信任/Kerberos原則 4713/4865-4867、
    /// DSRM 密碼嘗試 4794、NTFS 延遲寫入 137、BSOD 1001、MSSQL I/O 錯誤 823-825、ESENT 損毀 467/474、
    /// App Hang 1002）與 7 條 Linux 規則（磁碟耗盡、唯讀重掛、mdadm 降級、網卡中斷、crontab 編輯、
    /// fail2ban 封鎖、rsyslog 掉訊息），總計 92 條（Windows 64、Linux 28）。</summary>
    public const int Version = 5;

    public static List<KnownIssueRule> CreateRules() => new()
    {
        // ── 儲存裝置（硬碟故障最重要的前兆訊號）─────────────────────────
        new() { Id = "builtin-storage-disk-io", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "disk", EventIds = new[] { 7, 11, 51, 52, 153 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "磁碟 I/O 錯誤或壞軌前兆，硬碟可能即將故障，應盡快備份並安排更換",
                PlainExplanation = "這台伺服器的硬碟出現讀寫錯誤，是硬碟即將故障最直接的警訊。",
                Impact = "硬碟繼續惡化可能導致資料損毀、系統當機，甚至硬碟完全故障、資料無法救回。",
                LikelyCauses = new[] { "硬碟已達使用壽命末期（機械硬碟常見，SSD 也有寫入壽命問題）",
                    "硬碟本身有壞軌或韌體異常", "SATA/SAS 線材接觸不良或控制器異常" },
                NextSteps = new[] { "立即確認最新一次備份是否成功且可還原",
                    "用廠商工具（如 CrystalDiskInfo、smartctl）檢查硬碟 S.M.A.R.T. 健康狀態",
                    "安排更換硬碟，優先順序視錯誤頻率而定", "若為 RAID 陣列，確認其他磁碟健康、預留備援時間" } },
        new() { Id = "builtin-storage-ntfs-corruption", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Ntfs", EventIds = new[] { 55, 98, 130, 140, 141 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "NTFS 檔案系統損毀跡象，需執行 chkdsk 並檢查底層磁碟健康",
                PlainExplanation = "檔案系統本身的結構出現異常，代表磁碟上的資料組織方式可能已經受損。",
                Impact = "檔案系統損毀若持續惡化，可能造成檔案讀取錯誤、資料遺失，甚至系統無法開機。",
                LikelyCauses = new[] { "底層磁碟硬體故障（壞軌）", "非預期斷電或當機造成寫入中斷",
                    "磁碟機或控制器驅動程式問題" },
                NextSteps = new[] { "盡快排程執行 chkdsk /f 修復（需重開機或於維護時段執行）",
                    "chkdsk 前務必先確認備份", "同步檢查磁碟硬體健康狀況（見磁碟 I/O 錯誤處置）",
                    "若同一顆磁碟反覆出現，優先考慮更換硬體而非只修復檔案系統" } },
        new() { Id = "builtin-storage-controller-timeout", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "stor", EventIds = new[] { 129 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High,
                Description = "儲存控制器逾時重置 (storahci/stornvme 129)，常見於硬碟劣化、線材或背板異常",
                PlainExplanation = "儲存控制器對磁碟的指令逾時、自動重置連線，代表磁碟或連接路徑不穩定。",
                Impact = "偶發不一定立即造成問題，但頻繁發生代表儲存路徑劣化中，可能演變成磁碟離線或資料存取失敗。",
                LikelyCauses = new[] { "硬碟本身開始劣化", "SATA/SAS 線材或背板接觸不良",
                    "儲存控制器韌體或驅動程式問題", "磁碟陣列電源供應不穩" },
                NextSteps = new[] { "檢查該磁碟槽位的線材與背板連接", "確認控制器與磁碟韌體/驅動為最新版本",
                    "留意是否與磁碟 I/O 錯誤（Event 153 等）同時出現，若有代表故障已進入下一階段",
                    "持續發生應排查硬體或安排更換" } },
        new() { Id = "builtin-resource-disk-space-low", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "srv", EventIds = new[] { 2013 },
                Category = IssueCategory.Resource, Severity = IssueSeverity.Medium,
                Description = "磁碟空間即將不足",
                PlainExplanation = "系統偵測到磁碟剩餘空間即將用盡。",
                Impact = "空間耗盡後，服務可能因無法寫入暫存/日誌檔而異常，甚至系統本身無法正常運作。",
                LikelyCauses = new[] { "日誌檔、暫存檔或備份檔案持續累積未清理", "應用程式產生大量資料未歸檔",
                    "磁碟配置容量原本就偏小" },
                NextSteps = new[] { "立即檢查磁碟使用狀況，找出佔用空間最大的目錄",
                    "清理不需要的暫存檔/舊日誌/舊備份", "評估是否需要擴充磁碟容量或搬移資料" } },

        // ── 硬體（CPU / 記憶體 / 電源）───────────────────────────────
        new() { Id = "builtin-hardware-whea-error", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "WHEA-Logger",
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "WHEA 硬體錯誤 (CPU/記憶體/PCIe)。corrected error 次數上升是硬體劣化的典型前兆",
                PlainExplanation = "CPU、記憶體或 PCIe 匯流排偵測到硬體層級的錯誤，這是硬體開始劣化的訊號。",
                Impact = "corrected error（可修正錯誤）持續累積代表硬體正在劣化，若演變成 uncorrected error 可能直接導致當機或資料損毀。",
                LikelyCauses = new[] { "記憶體模組故障或接觸不良", "CPU 過熱或供電不穩",
                    "主機板或 PCIe 裝置（如網卡、擴充卡）異常", "機房環境溫濕度異常" },
                NextSteps = new[] { "記錄錯誤發生頻率與趨勢，確認是否持續上升",
                    "檢查主機板 BIOS/韌體是否為最新版本", "安排硬體診斷（記憶體測試、CPU 溫度監控）",
                    "頻率持續上升時，安排在下個維護窗口更換可疑硬體元件" } },
        new() { Id = "builtin-hardware-kernel-power-41", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Kernel-Power", EventIds = new[] { 41 },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "非預期斷電或當機重開 (Kernel-Power 41)，可能為電源、過熱或硬體不穩",
                PlainExplanation = "系統沒有正常關機程序就重新啟動了，通常代表突發斷電、當機或硬體異常。",
                Impact = "重複發生代表電源、散熱或硬體有間歇性問題，可能導致資料未寫入完成而損毀，或演變成更嚴重的當機。",
                LikelyCauses = new[] { "電源供應器（PSU）故障或不穩", "UPS 異常或未正確供電",
                    "硬體過熱自動保護關機", "驅動程式或核心層級當機" },
                NextSteps = new[] { "檢查該時間點的電力紀錄與 UPS 日誌", "確認機房溫度與伺服器散熱狀況",
                    "檢查電源供應器健康狀態", "若排除電力因素，安排硬體診斷排查主機板/記憶體/CPU" } },
        new() { Id = "builtin-hardware-unexpected-shutdown-6008", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "EventLog", EventIds = new[] { 6008 },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High,
                Description = "非預期關機",
                PlainExplanation = "系統前一次關機沒有走正常程序，等於是非計劃性的停機。",
                Impact = "偶發可能只是人為誤觸或短暫斷電；頻繁發生則代表系統穩定性有問題。",
                LikelyCauses = new[] { "斷電或電力不穩", "系統當機後自動或被迫重開", "人員未依正常程序關機" },
                NextSteps = new[] { "對照 Kernel-Power 41 等相關事件，確認是否為同一次事件的不同紀錄",
                    "檢查電力與 UPS 狀況", "頻繁發生時視同硬體不穩處理，排查電源與散熱" } },
        new() { Id = "builtin-resource-exhaustion", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "Resource-Exhaustion",
                Category = IssueCategory.Resource, Severity = IssueSeverity.High,
                Description = "系統資源（虛擬記憶體）即將耗盡，可能有程式記憶體洩漏",
                PlainExplanation = "系統的虛擬記憶體（分頁檔）即將用盡。",
                Impact = "虛擬記憶體耗盡會導致應用程式配置記憶體失敗、服務異常或系統整體回應變慢甚至當機。",
                LikelyCauses = new[] { "某個程式有記憶體洩漏，用量持續增加不釋放", "實體記憶體不足、過度依賴分頁檔",
                    "同時執行過多服務或程式" },
                NextSteps = new[] { "用工作管理員/效能監視器找出記憶體用量異常增長的程序",
                    "重啟疑似洩漏的服務作為短期緩解", "評估是否需要增加實體記憶體",
                    "追查該程式是否有已知的記憶體洩漏問題並更新修補" } },

        // ── 服務 ────────────────────────────────────────────────
        new() { Id = "builtin-service-crash-loop-703x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7031, 7034 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "服務異常終止；反覆發生代表服務不穩定，需檢查應用程式錯誤",
                PlainExplanation = "某個 Windows 服務不正常地停止運作。",
                Impact = "偶發通常無害（服務會自動重啟）；反覆發生代表該服務本身或其依賴的程式不穩定，可能影響對應功能的可用性。",
                LikelyCauses = new[] { "服務程式本身有錯誤（未處理的例外）", "服務依賴的資源（資料庫、網路、檔案）暫時無法使用",
                    "資源不足（記憶體/CPU）導致服務被系統終止" },
                NextSteps = new[] { "查看該服務對應的應用程式日誌，找出真正的錯誤原因",
                    "確認服務依賴的資源（DB 連線、網路、憑證）是否正常",
                    "若反覆發生，考慮設定服務自動修復動作並持續觀察",
                    "必要時聯繫應用程式廠商或開發團隊排查" } },
        new() { Id = "builtin-service-start-failure-700x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7000, 7001 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium,
                Description = "服務啟動失敗",
                PlainExplanation = "某個 Windows 服務在啟動時失敗，沒有成功執行。",
                Impact = "該服務對應的功能將無法使用，若是關鍵服務（如資料庫、網路服務）會直接影響系統可用性。",
                LikelyCauses = new[] { "服務所需的相依服務未啟動或啟動失敗", "設定檔錯誤或遺失",
                    "服務帳戶權限不足或密碼過期", "執行檔或相依元件損毀/遺失" },
                NextSteps = new[] { "確認該服務的相依服務是否都已正常啟動", "檢查服務帳戶的密碼與權限是否有效",
                    "查看服務對應的詳細錯誤訊息與應用程式日誌", "嘗試手動啟動服務觀察即時錯誤" } },
        new() { Id = "builtin-security-new-service-7045", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7045 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "系統安裝了新服務——若非管理員預期的操作，可能是入侵者植入後門",
                PlainExplanation = "系統上被安裝了一個新的 Windows 服務。",
                Impact = "若非管理員預期的操作，這可能是入侵者植入的後門或惡意程式，一旦成立會讓攻擊者取得持續存取能力。",
                LikelyCauses = new[] { "合法的軟體安裝或系統更新（最常見情況）", "管理員手動安裝新服務進行維運",
                    "入侵者植入的持久化後門" },
                NextSteps = new[] { "確認是否為已知/預期的軟體安裝或維運操作",
                    "若無法確認來源，檢查該服務的執行檔路徑、簽章與建立時間",
                    "非預期時立即停用該服務並進一步鑑識調查",
                    "確認的合法安裝可標記為已知雜訊，供規則表未來調整參考" } },

        // ── 營運健康（備份、時間、憑證、網域設定）────────────────────
        new() { Id = "builtin-backup-failure-517", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Backup", EventIds = new[] { 517 },
                Category = IssueCategory.Backup, Severity = IssueSeverity.High,
                Description = "Windows Server Backup 備份失敗——備份損壞往往到需要還原時才發現，應立即檢查",
                PlainExplanation = "Windows Server Backup 的備份工作失敗了。",
                Impact = "備份失敗往往在真正需要還原資料時才會被發現，屆時可能已經沒有可用的備份可供救援。",
                LikelyCauses = new[] { "備份目標磁碟/位置空間不足或無法存取", "備份的來源磁碟區有錯誤（如磁碟/檔案系統問題）",
                    "備份服務或 VSS 元件異常", "備份排程與其他工作衝突" },
                NextSteps = new[] { "立即查看備份失敗的詳細錯誤訊息", "確認備份目的地（磁碟/網路共用）空間與連線正常",
                    "手動重跑一次備份確認是否可成功", "找出最近一次成功備份的時間點，評估目前的資料風險缺口" } },
        new() { Id = "builtin-backup-vss-error", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "VSS",
                Category = IssueCategory.Backup, Severity = IssueSeverity.Medium,
                Description = "磁碟區陰影複製 (VSS) 錯誤，會導致備份失敗或不完整",
                PlainExplanation = "磁碟區陰影複製服務 (VSS) 發生錯誤，這是備份與還原點功能背後的關鍵元件。",
                Impact = "VSS 異常會導致備份失敗或不完整，也會影響還原點/快照功能無法正常使用。",
                LikelyCauses = new[] { "磁碟空間不足導致 VSS 儲存區無法配置", "VSS 相關服務未正常啟動",
                    "第三方應用程式的 VSS writer 異常", "磁碟本身有健康問題" },
                NextSteps = new[] { "用 vssadmin list writers 檢查是否有 writer 處於錯誤狀態",
                    "確認磁碟可用空間充足", "重啟 Volume Shadow Copy 相關服務", "確認後續備份工作是否恢復正常" } },
        new() { Id = "builtin-config-time-sync-failure", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Time-Service", EventIds = new[] { 29, 36, 47, 50 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "時間同步失敗；時鐘偏移超過 5 分鐘會導致 Kerberos 驗證與網域登入全面失敗",
                PlainExplanation = "系統與時間伺服器的時間同步失敗，伺服器時鐘可能開始偏移。",
                Impact = "時鐘偏移超過約 5 分鐘會導致 Kerberos 驗證失敗，使用者與服務可能突然無法登入或存取網域資源。",
                LikelyCauses = new[] { "無法連線到時間來源伺服器（網路問題或設定錯誤）", "時間伺服器本身異常",
                    "網域控制站的時間服務設定問題" },
                NextSteps = new[] { "確認可以連線到設定的時間來源（NTP server / 網域中的 PDC）",
                    "手動執行 w32tm /resync 測試同步", "檢查目前時鐘偏移量，若已偏移應盡快手動校正",
                    "確認網域時間架構設定正確（PDC Emulator 角色）" } },
        new() { Id = "builtin-config-cert-expiring-64", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "AutoEnrollment", EventIds = new[] { 64 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "憑證即將到期——過期會造成 TLS 或服務中斷，是最容易預防的停機原因之一",
                PlainExplanation = "系統上有一張憑證即將到期。",
                Impact = "憑證過期後，依賴它的 TLS 連線、服務驗證會失敗，可能造成無預警的服務中斷。",
                LikelyCauses = new[] { "憑證自動更新（AutoEnrollment）失敗或未設定", "憑證授權單位（CA）連線異常",
                    "手動核發的憑證到期前未安排更新" },
                NextSteps = new[] { "確認是哪張憑證即將到期（用途、使用它的服務）", "檢查自動註冊/更新是否正常運作",
                    "無法自動更新時安排手動更新流程", "更新完成後確認相關服務已載入新憑證" } },
        new() { Id = "builtin-config-schannel-36870", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Schannel", EventIds = new[] { 36870 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "TLS 憑證私鑰存取失敗，常見於憑證過期或權限異常",
                PlainExplanation = "系統嘗試使用 TLS 憑證的私鑰時失敗，通常代表憑證有問題或存取權限異常。",
                Impact = "會導致使用該憑證的 TLS/SSL 連線（如 HTTPS、LDAPS）建立失敗，服務對外連線可能中斷。",
                LikelyCauses = new[] { "憑證已過期或已被撤銷", "私鑰檔案的存取權限被異動，服務帳戶無法讀取",
                    "憑證存放區異常" },
                NextSteps = new[] { "確認相關憑證是否已過期（對照憑證即將到期告警）",
                    "檢查該憑證私鑰的存取權限（ACL）是否正確", "必要時重新匯入或重新核發憑證",
                    "確認相關服務（如 IIS）在憑證更新後已重啟載入" } },
        new() { Id = "builtin-config-group-policy-failure", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "GroupPolicy", EventIds = new[] { 1030, 1058 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "群組原則套用失敗，可能為 SYSVOL 或網域控制站連線問題",
                PlainExplanation = "群組原則 (Group Policy) 套用失敗，代表主機無法正確取得網域管理的設定。",
                Impact = "持續失敗會讓伺服器逐漸偏離公司標準設定（安全性原則、軟體限制等），也可能是 SYSVOL 或網域連線更大問題的前兆。",
                LikelyCauses = new[] { "無法連線到網域控制站或 SYSVOL 共用資料夾", "DNS 解析網域控制站失敗",
                    "網路連線問題或防火牆阻擋", "群組原則物件本身設定錯誤" },
                NextSteps = new[] { "執行 gpupdate /force 並觀察詳細錯誤訊息",
                    "確認主機可以正常解析並連線到網域控制站", "檢查 SYSVOL 共用資料夾的存取權限",
                    "持續失敗應同步檢查該主機的網域信任關係是否正常" } },
        new() { Id = "builtin-config-netlogon-5719", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "NETLOGON", EventIds = new[] { 5719 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "無法連上網域控制站，網域驗證將受影響",
                PlainExplanation = "系統無法連線到網域控制站，這會影響網域登入與驗證功能。",
                Impact = "持續無法連線會導致使用網域帳號的登入失敗、群組原則無法套用，嚴重時整台伺服器形同脫離網域管理。",
                LikelyCauses = new[] { "網路連線中斷或不穩定", "DNS 設定錯誤，無法解析網域控制站",
                    "網域控制站本身故障或離線", "伺服器的電腦帳戶密碼與網域不同步" },
                NextSteps = new[] { "確認伺服器網路連線與 DNS 設定正常", "確認至少一台網域控制站可正常連線",
                    "檢查是否為網域控制站端的問題（其他伺服器是否也受影響）",
                    "持續發生時考慮用 netdom 重置電腦帳戶信任關係" } },
        new() { Id = "builtin-resource-dhcp-pool-low", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "DhcpServer", EventIds = new[] { 1020 },
                Category = IssueCategory.Resource, Severity = IssueSeverity.Medium,
                Description = "DHCP 位址池即將耗盡，新裝置將無法取得 IP（僅 DHCP 伺服器角色會出現）",
                PlainExplanation = "DHCP 伺服器可分配的 IP 位址即將用完。",
                Impact = "位址池耗盡後，新裝置連上網路將無法取得 IP，形同無法連網。",
                LikelyCauses = new[] { "位址池範圍設定原本就偏小", "租約時間過長，IP 未及時回收",
                    "網路上裝置數量成長超出原始規劃", "有裝置異常佔用大量 IP（如訪客網路濫用）" },
                NextSteps = new[] { "檢查目前位址池使用率與可用剩餘量", "評估是否可縮短租約時間加速回收",
                    "評估擴充位址池範圍（新增子網段或調整遮罩）", "排查是否有異常裝置佔用大量 IP" } },
        new() { Id = "builtin-service-app-crash-1000", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Application Error", EventIds = new[] { 1000 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "應用程式反覆崩潰——服務完全掛掉之前通常先出現這個訊號",
                PlainExplanation = "某個應用程式反覆發生錯誤崩潰。",
                Impact = "反覆崩潰通常是服務即將完全無法使用的前兆，也可能造成資料未儲存或處理中斷。",
                LikelyCauses = new[] { "應用程式本身有臭蟲（未處理的例外）", "應用程式相依的元件或函式庫版本不相容",
                    "資源不足（記憶體/磁碟）導致執行異常", "資料損毀或輸入異常觸發程式錯誤" },
                NextSteps = new[] { "記錄崩潰的應用程式名稱、模組與錯誤代碼，查詢是否為已知問題",
                    "確認該應用程式與相依元件是否需要更新/修補", "檢查系統資源是否充足",
                    "若為自行開發的應用程式，將錯誤資訊回報開發團隊排查" } },
        new() { Id = "builtin-service-dotnet-exception-1026", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = ".NET Runtime", EventIds = new[] { 1026 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = ".NET 應用程式未處理例外反覆發生",
                PlainExplanation = "某個 .NET 應用程式反覆發生未處理的程式錯誤。",
                Impact = "反覆發生代表該應用程式不穩定，可能導致功能中斷或資料處理錯誤，情況惡化可能造成服務完全停擺。",
                LikelyCauses = new[] { "程式邏輯錯誤（未處理的例外狀況）", ".NET Runtime 版本與應用程式不相容",
                    "應用程式相依的外部資源（資料庫、API）異常" },
                NextSteps = new[] { "查看完整例外堆疊，找出實際發生錯誤的程式模組",
                    "確認 .NET Runtime 版本是否符合應用程式需求",
                    "回報開發團隊修補，並評估是否需要暫時的因應措施（如自動重啟）" } },
        new() { Id = "builtin-config-windows-update-failure-20", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "WindowsUpdateClient", EventIds = new[] { 20 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Low,
                Description = "Windows Update 安裝失敗，持續失敗累積未修補的安全風險",
                PlainExplanation = "Windows Update 的更新安裝失敗。",
                Impact = "單次失敗風險不高，但持續累積會讓系統長期缺乏安全性修補，增加被已知漏洞攻擊的風險。",
                LikelyCauses = new[] { "更新元件本身損毀，需要修復工具處理", "磁碟空間不足",
                    "與其他已安裝的軟體/更新衝突", "網路連線中斷導致下載失敗" },
                NextSteps = new[] { "查看具體失敗的更新項目與錯誤代碼", "確認磁碟空間是否充足",
                    "嘗試執行 Windows Update 疑難排解工具或手動安裝該更新",
                    "持續失敗應排入定期維護清單，避免長期未修補" } },

        // ── 安全 / 入侵跡象（Security log）──────────────────────────
        new() { Id = "builtin-security-bruteforce-4625", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4625 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "登入失敗；短時間大量發生代表帳號密碼暴力破解攻擊",
                PlainExplanation = "短時間內出現大量登入失敗，這是帳號密碼暴力破解攻擊的典型特徵。",
                Impact = "若攻擊持續且密碼強度不足，攻擊者可能成功登入取得帳號的存取權限，進一步在系統內活動。",
                LikelyCauses = new[] { "外部或內部來源對特定帳號進行密碼猜測攻擊",
                    "自動化掃描工具對開放服務（如 RDP）進行帳密嘗試",
                    "合法使用者密碼設定錯誤持續重試（機率較低但需排除）" },
                NextSteps = new[] { "確認攻擊來源 IP 與被嘗試的帳號，評估是否需要封鎖來源",
                    "確認相關帳號密碼是否仍安全（未被猜中）——比對是否有同組帳號/IP 的成功登入",
                    "檢查該服務是否有必要對外開放，或加上多因素驗證/IP 白名單",
                    "考慮啟用帳戶鎖定原則降低暴力破解成功機率" } },
        new() { Id = "builtin-security-account-lockout-4740", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4740 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被鎖定，通常是暴力破解的結果",
                PlainExplanation = "有一個使用者帳戶因為連續登入失敗而被系統自動鎖定。",
                Impact = "通常是暴力破解攻擊的結果，也可能是使用者忘記密碼的正常情況——需要判讀是哪一種才能決定後續動作。",
                LikelyCauses = new[] { "暴力破解攻擊觸發帳戶鎖定原則", "使用者本人忘記密碼多次嘗試",
                    "應用程式或排程工作使用過期密碼持續重試" },
                NextSteps = new[] { "對照是否有同帳號的大量登入失敗（4625），確認是否為攻擊所致",
                    "聯繫帳戶擁有者確認是否為本人操作",
                    "若為攻擊，追查來源並考慮加強防護；若為誤鎖，依正常流程解鎖" } },
        new() { Id = "builtin-security-audit-log-cleared-1102", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 1102 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "安全稽核日誌被清除——入侵者滅跡的典型行為，應立即調查",
                PlainExplanation = "伺服器的安全稽核日誌被清除了——這是攻擊者入侵後常見的滅跡行為。",
                Impact = "日誌被清除代表清除時間點之前的活動紀錄已經遺失，會嚴重影響後續的入侵調查與鑑識工作。",
                LikelyCauses = new[] { "入侵者取得管理權限後清除紀錄以掩蓋行蹤",
                    "管理員的正常維運操作（如日誌歸檔前清空）——需確認是否為預期行為", "自動化的日誌管理工具設定" },
                NextSteps = new[] { "立即確認是否為已知的管理操作（誰在什麼時候執行的）",
                    "若無法確認來源，視為入侵事件立即啟動調查程序",
                    "檢查該時間點前後是否有其他異常活動（其他主機的登入、權限異動等）",
                    "確認是否有其他日誌來源（如集中式 SIEM）保留了被清除前的紀錄" } },
        new() { Id = "builtin-security-audit-policy-changed-4719", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4719 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "稽核原則被變更，可能是入侵者關閉記錄以躲避偵測",
                PlainExplanation = "系統的安全稽核原則被變更了，這可能會讓某些活動不再被記錄。",
                Impact = "若被入侵者用來關閉特定稽核項目，後續的惡意活動將不會留下紀錄，等於製造了偵測死角。",
                LikelyCauses = new[] { "管理員調整稽核原則以符合合規或效能需求", "入侵者關閉稽核以躲避後續行為被記錄" },
                NextSteps = new[] { "確認變更是否為已知的管理操作",
                    "檢查變更後的稽核原則內容，確認關鍵項目（登入、帳戶管理等）是否仍在記錄",
                    "非預期變更時視為可疑，進一步調查操作來源" } },
        new() { Id = "builtin-security-account-created-472x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4720, 4722, 4724 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶建立/啟用/密碼被重設——若非預期操作可能為入侵者建立立足點",
                PlainExplanation = "有新的使用者帳戶被建立、被啟用，或有人的密碼被重設。",
                Impact = "若非預期操作，可能是入侵者建立自己的後門帳號，或竄改既有帳號密碼以取得存取權。",
                LikelyCauses = new[] { "IT 人員正常的帳號建立/管理作業", "入侵者建立新帳號作為立足點",
                    "入侵者重設既有帳號密碼以取得控制權" },
                NextSteps = new[] { "確認是否為已知的帳戶管理操作及執行者",
                    "非預期時立即檢查該帳號的權限範圍與近期活動",
                    "確認被重設密碼的帳戶本人是否知情，若非本人請求應視為可疑" } },
        new() { Id = "builtin-security-privileged-group-add-47xx", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4728, 4732, 4756 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被加入特權群組（如 Administrators），需確認是否為授權操作——典型提權手法",
                PlainExplanation = "有帳戶被加入了 Administrators 等特權群組，取得更高的系統權限。",
                Impact = "若非授權操作，代表攻擊者已完成權限提升，能對系統做幾乎任何事，風險等級極高。",
                LikelyCauses = new[] { "管理員授權的正常權限調整", "入侵者取得初始存取後進行權限提升的典型手法" },
                NextSteps = new[] { "立即確認是誰、為何將該帳戶加入特權群組",
                    "非預期時立即將該帳戶移出特權群組並鎖定調查",
                    "檢查該帳戶近期的其他活動，評估是否已造成損害" } },
        new() { Id = "builtin-security-privileged-group-remove-47xx", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4729, 4733, 4757 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被移出特權群組，需確認是否為授權操作——也可能是入侵者提權得手後移除紀錄以滅跡",
                PlainExplanation = "有帳戶被移出了特權群組。",
                Impact = "多數情況是正常的權限回收；但也可能是入侵者提權得手後移除操作紀錄以滅跡，需要一併確認情境。",
                LikelyCauses = new[] { "管理員正常的權限回收作業（如人員離職、專案結束）",
                    "入侵者清除自己曾經被加入特權群組的痕跡" },
                NextSteps = new[] { "確認變更是否為已知的權限管理操作",
                    "對照是否同時有該帳戶先前被加入特權群組的紀錄，評估是否為滅跡行為",
                    "非預期時比照入侵事件調查" } },
        new() { Id = "builtin-security-persistence-service-task-469x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4697, 4698 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "安裝服務或建立排程任務——攻擊者常見的持久化手法",
                PlainExplanation = "系統上有新服務被安裝，或有新的排程任務被建立。",
                Impact = "這是攻擊者常見的持久化手法——即使當下被發現，也能透過排程或服務在之後重新啟動惡意程式。",
                LikelyCauses = new[] { "合法的軟體安裝或維運排程設定", "入侵者植入的持久化機制" },
                NextSteps = new[] { "確認是否為已知的安裝或排程設定操作",
                    "檢查新服務/排程任務的執行內容、路徑與觸發時間是否合理",
                    "非預期時立即停用並進一步鑑識調查來源" } },

        // ── 權限與角色異動（無論授予或移除都要關注）──────────────────────
        new() { Id = "builtin-security-acl-changed-4670", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4670 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "檔案／資料夾／登錄物件的權限 (ACL) 被變更，需確認是否為授權操作",
                PlainExplanation = "檔案、資料夾或登錄機碼的存取權限 (ACL) 被變更。",
                Impact = "若被入侵者用來放寬敏感資源的存取權限，可能為後續竊取資料或持久化鋪路。",
                LikelyCauses = new[] { "管理員正常的權限調整作業", "入侵者調整權限以利後續存取或植入惡意程式" },
                NextSteps = new[] { "確認變更的物件是什麼、變更內容為何", "確認是否為已知的授權操作",
                    "非預期時檢查該物件目前的存取權限是否合理，並追查異動來源" } },
        new() { Id = "builtin-security-sacl-changed-4907", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4907 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "物件的稽核設定 (SACL) 被變更——可能是入侵者針對特定物件關閉稽核記錄以躲避偵測",
                PlainExplanation = "某個物件的稽核設定被變更，可能導致該物件之後的存取行為不再被記錄。軟體安裝與系統更新也會變更稽核設定，需對照當日是否有預期的更新作業。",
                Impact = "這是針對性關閉稽核的手法，代表攻擊者可能已鎖定特定敏感物件（檔案、機碼），意圖在該處活動而不留紀錄。",
                LikelyCauses = new[] { "管理員調整特定物件的稽核設定", "入侵者針對性關閉敏感物件的稽核追蹤" },
                NextSteps = new[] { "確認是哪個物件、變更了什麼稽核設定", "確認是否為已知操作",
                    "非預期時視為高度可疑，優先調查該物件近期的存取紀錄與相關帳戶活動" } },
        new() { Id = "builtin-security-user-rights-4717", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4717, 4718 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "系統存取權限被授予/移除（User Rights Assignment），需確認是否為授權操作",
                PlainExplanation = "使用者權限指派 (User Rights Assignment) 被變更，例如「以服務身分登入」等系統層級權限。",
                Impact = "這類權限直接影響帳戶能執行的系統層級操作，若被濫用可能繞過一般的存取控制。",
                LikelyCauses = new[] { "管理員設定服務帳戶或應用程式所需的系統權限",
                    "入侵者授予自己控制的帳戶額外的系統層級權限" },
                NextSteps = new[] { "確認變更內容（哪個權限、授予給誰）與操作者", "確認是否為已知的系統設定操作",
                    "非預期時檢查該帳戶目前擁有的完整權限範圍" } },
        new() { Id = "builtin-security-user-rights-assignment-4704", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4704, 4705 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "使用者權限指派被新增/移除，影響帳戶可執行的系統層級操作範圍",
                PlainExplanation = "帳戶被新增或移除了特定的使用者權限指派。",
                Impact = "影響帳戶可執行的系統層級操作範圍，若遭濫用可能讓一般帳戶取得原本不該有的能力。",
                LikelyCauses = new[] { "管理員的系統設定調整", "入侵者調整帳戶權限以利後續操作" },
                NextSteps = new[] { "確認變更內容與操作者是否為已知操作",
                    "非預期時檢查該帳戶目前完整權限並評估風險" } },
        new() { Id = "builtin-security-token-privilege-4703", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4703 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "權杖 (token) 特殊權限於執行期間被調整——常見的權限提升攻擊手法",
                PlainExplanation = "某個帳戶在執行期間被調整了權杖 (token) 上的特殊權限，這是常見的權限提升攻擊手法。新版 Windows 上系統行程會例行產生此事件，少量出現屬正常。",
                Impact = "攻擊者常利用此手法讓程式暫時取得超出帳戶原本範圍的權限，執行原本無法做到的操作。",
                LikelyCauses = new[] { "系統或應用程式的正常權限調整行為（部分合法程式運作機制）",
                    "入侵者利用漏洞或工具進行權限提升攻擊" },
                NextSteps = new[] { "確認觸發此事件的程式與帳戶是否為已知、可信的",
                    "非預期或來源不明時，視為可疑的權限提升嘗試進行調查",
                    "檢查該時間點前後是否有其他異常活動" } },
        new() { Id = "builtin-security-group-changed-4735", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4735 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "安全群組的內容或權限被變更",
                PlainExplanation = "某個安全群組的內容或權限設定被變更。",
                Impact = "若該群組具有重要權限，變更可能間接影響大量帳戶的存取範圍。",
                LikelyCauses = new[] { "管理員的正常群組管理作業", "入侵者變更群組設定以擴大自己或其他帳戶的存取權" },
                NextSteps = new[] { "確認是哪個群組、變更了什麼內容", "確認是否為已知操作",
                    "非預期時評估此群組成員的權限範圍與潛在影響" } },
        new() { Id = "builtin-security-domain-policy-changed-4739", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4739 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "網域原則被變更（僅網域控制站），影響範圍可能擴及整個網域",
                PlainExplanation = "網域等級的原則被變更了（僅網域控制站會出現），影響範圍可能涵蓋整個網域。",
                Impact = "網域原則變更影響所有加入該網域的電腦與使用者，若為惡意變更，波及範圍會遠大於單一主機事件。",
                LikelyCauses = new[] { "網域管理員的正常原則調整", "取得網域控制站權限的入侵者進行破壞性或提權變更" },
                NextSteps = new[] { "確認變更是否為已知的網域管理操作及執行者",
                    "非預期時視為高度嚴重事件，立即調查並考慮暫時還原原則",
                    "檢查是否有其他網域控制站也出現異常" } },
        new() { Id = "builtin-security-local-group-4731", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4731, 4734 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "本機安全群組被建立/刪除，需確認是否為授權操作",
                PlainExplanation = "本機層級有安全群組被建立或刪除。",
                Impact = "本機群組通常影響範圍侷限於單一主機，但仍可能被用來規避既有的權限控管設計。",
                LikelyCauses = new[] { "管理員的本機帳戶管理作業", "入侵者建立群組作為權限管理或立足點的一部分" },
                NextSteps = new[] { "確認是否為已知的本機管理操作", "非預期時檢查該群組的成員與被賦予的權限" } },

        // ── Microsoft Defender（Operational 頻道，2026-07 EventLogReader 遷移後可讀）─────────
        // Defender 事件天生低誤報：偵測到惡意程式本身就是明確訊號。分級的關鍵在「已處置 vs 處置失敗」
        // 與「防護被關閉」——不做「1116 之後沒看到 1117」這類缺席推論（資料不完整時會誤報）。
        new() { Id = "builtin-defender-malware-detected-1006-1116", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 1006, 1116 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "Microsoft Defender 偵測到惡意程式（1006/1116），應確認處置結果與感染來源",
                PlainExplanation = "防毒軟體在這台伺服器上發現了惡意程式。",
                Impact = "惡意程式可能竊取資料、加密勒索、作為入侵者的立足點，或橫向擴散到其他主機。",
                LikelyCauses = new[] { "使用者下載或執行了受感染的檔案", "入侵者植入的惡意程式或後門",
                    "受感染的隨身碟／網路共享", "既有感染在掃描時才被發現" },
                NextSteps = new[] { "確認 Defender 是否已成功隔離/移除（對應 1007/1117 處置事件）",
                    "查明惡意程式的檔案路徑與來源，評估感染範圍", "若處置失敗（1008/1118/1119）應立即隔離該主機",
                    "檢查同時段是否有帳號建立/提權/新服務等入侵跡象" } },
        new() { Id = "builtin-defender-malware-handled-1007-1117", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 1007, 1117 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "Microsoft Defender 已對惡意程式採取處置（1007/1117，如隔離/移除）",
                PlainExplanation = "防毒軟體已對偵測到的惡意程式採取處置動作（例如隔離或移除）。",
                Impact = "已處置代表立即威脅降低，但仍需查明感染來源，避免同一途徑再次被感染。",
                LikelyCauses = new[] { "Defender 對先前偵測到的惡意程式自動採取隔離/清除", "使用者或管理員手動處置" },
                NextSteps = new[] { "確認處置確實成功（狀態非失敗）", "追查感染來源與範圍，處理根因而非只清除結果",
                    "留意是否有其他主機出現同一惡意程式" } },
        new() { Id = "builtin-defender-malware-action-failed-1008-1118-1119", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 1008, 1118, 1119 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "Microsoft Defender 對惡意程式的處置失敗（1008/1118/1119），惡意程式可能仍活躍",
                PlainExplanation = "防毒軟體嘗試處置惡意程式但失敗了，威脅可能仍然存在於系統中。",
                Impact = "處置失敗代表惡意程式可能仍在執行或潛伏，持續造成危害或作為入侵跳板。",
                LikelyCauses = new[] { "惡意程式主動抵抗移除（如常駐於執行中的程序）",
                    "檔案被鎖定或權限不足", "惡意程式已取得較高權限、干擾防毒運作" },
                NextSteps = new[] { "立即將該主機從網路隔離，防止擴散", "以離線掃描工具或重開機至安全模式再次處置",
                    "確認惡意程式的持久化位置（服務、排程、登錄）", "評估是否需要重建系統，並全面稽查該主機的帳號與活動" } },
        new() { Id = "builtin-defender-rtp-disabled-5001", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 5001 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "Microsoft Defender 即時防護被關閉（5001），可能是入侵者為植入惡意程式而先解除防護",
                PlainExplanation = "防毒軟體的即時防護被關閉了，這台伺服器目前處於沒有即時防護的狀態。",
                Impact = "即時防護關閉期間，惡意程式可以不受阻擋地執行；入侵者常在植入惡意程式前先關閉防護。",
                LikelyCauses = new[] { "管理員或安裝程式為相容性暫時關閉（多數情況屬正常維運）",
                    "群組原則或第三方防毒接管", "入侵者為規避偵測而主動關閉防護" },
                NextSteps = new[] { "確認關閉是否為已知的授權操作與執行者", "非預期時立即重新啟用即時防護並全機掃描",
                    "檢查關閉前後是否出現惡意程式偵測或其他入侵跡象", "確認是否有第三方防毒接管（屬正常，見 5010/5012）" } },
        new() { Id = "builtin-defender-av-disabled-5010-5012", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 5010, 5012 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "Microsoft Defender 的防毒/掃描被停用（5010/5012），需確認是否為第三方防毒接管",
                PlainExplanation = "Defender 的病毒掃描或防毒功能被停用了。",
                Impact = "若沒有其他防毒接手，這台主機將失去惡意程式防護；若是第三方防毒接管則屬正常。",
                LikelyCauses = new[] { "安裝了第三方防毒軟體，Defender 自動退居被動（正常情境）",
                    "管理員或原則主動停用", "入侵者停用防毒以規避偵測" },
                NextSteps = new[] { "確認是否有第三方防毒正在運作、防護未中斷", "非預期停用時重新啟用並掃描",
                    "確認停用是否對應到已知的軟體安裝或原則變更" } },
        new() { Id = "builtin-defender-scan-failed-1005", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 1005 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "Microsoft Defender 掃描失敗（1005），防護涵蓋率可能不完整",
                PlainExplanation = "防毒軟體的掃描沒有正常完成。",
                Impact = "掃描失敗代表部分檔案未被檢查，潛在的惡意程式可能因此沒被發現。",
                LikelyCauses = new[] { "掃描過程被中斷（關機、資源不足）", "檔案被鎖定或損毀導致掃描出錯",
                    "Defender 元件或病毒碼異常" },
                NextSteps = new[] { "手動重新執行一次完整掃描確認能否完成", "檢查是否有系統資源不足或磁碟錯誤",
                    "持續失敗時確認 Defender 服務與病毒碼狀態" } },
        new() { Id = "builtin-defender-update-failed-200x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Windows Defender", EventIds = new[] { 2001, 2003, 2004 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "Microsoft Defender 病毒碼/引擎更新失敗（2001/2003/2004），持續失敗會使防護過時",
                PlainExplanation = "防毒軟體的病毒碼或引擎更新失敗了。",
                Impact = "病毒碼過時會讓防毒無法辨識新型惡意程式，防護等於漏洞越來越大。",
                LikelyCauses = new[] { "網路連線問題無法連上更新伺服器", "更新來源設定錯誤或代理伺服器阻擋",
                    "磁碟空間不足或權限問題" },
                NextSteps = new[] { "確認主機能否連上 Windows Update／WSUS／更新來源",
                    "手動觸發一次病毒碼更新確認能否成功", "偶發一兩次多為暫時性網路問題，連續失敗才需深入排查" } },

        // ── RDP 遠端桌面（TerminalServices Operational 頻道）─────────────────
        // **這兩條規則刻意設為 Low：正常遠端桌面使用即會產生，本身不是告警訊號。** 收集目的是提供
        // 關聯分析（【破解得手】【暴力破解→RDP 得手】需要成功登入的帳號/IP）與趨勢基準。Low 不參與
        // 風險判定（ComputeRuleBasedRisk 只看 ElevatesDayRisk 旗標與 High 嚴重度）、
        // 不觸發「首次出現」告警（門檻 ≥High），
        // 所以日常 RDP 維運、重複登入、新員工首次登入都不會產生任何告警——入侵訊號一律經由「有錨點」
        // 的確定性關聯（暴力破解達門檻 + 帳號/IP 交集）才成立，見 CorrelationAnalyzer。
        new() { Id = "builtin-rdp-session-events-21-24-25", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "TerminalServices-LocalSessionManager", EventIds = new[] { 21, 24, 25 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Low,
                Description = "遠端桌面工作階段事件（登入/中斷/重連）——正常遠端使用即會產生，收集供關聯與趨勢分析，本身非告警",
                PlainExplanation = "有人透過遠端桌面登入、中斷或重新連線這台伺服器。日常遠端維運會正常產生這些紀錄。",
                Impact = "單筆事件屬正常運作；只有在與大量登入失敗等攻擊訊號的帳號/IP 交集時，才代表可能是入侵得手。",
                LikelyCauses = new[] { "管理員或使用者的正常遠端桌面連線", "自動化工具或跳板機的遠端工作階段" },
                NextSteps = new[] { "正常情況無需處理", "僅在同時出現大量登入失敗、且帳號/IP 相符時才需視為入侵得手調查" } },
        new() { Id = "builtin-rdp-auth-success-1149", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "TerminalServices-RemoteConnectionManager", EventIds = new[] { 1149 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Low,
                Description = "遠端桌面驗證成功（1149）——正常遠端使用即會產生，收集供關聯與趨勢分析，本身非告警",
                PlainExplanation = "有人通過遠端桌面的身分驗證、成功連上這台伺服器。日常遠端維運會正常產生此紀錄。",
                Impact = "單筆事件屬正常運作；只有在與同組帳號/IP 的大量登入失敗交集時，才代表暴力破解可能已得手。",
                LikelyCauses = new[] { "管理員或使用者通過遠端桌面驗證", "自動化或跳板機的遠端連線" },
                NextSteps = new[] { "正常情況無需處理", "僅在與大量登入失敗的帳號/IP 相符時才需視為破解得手調查" } },

        // ── Windows 補強規則（seed v5：帳號生命週期、排程/防火牆、日誌清除、儲存/硬體延伸）─────
        // 4771：動態密碼(OTP)登入後未登出、隔天密碼變更造成的殘留憑證重試最典型表現即大量 4771，門檻 10 避免誤報。
        new() { Id = "builtin-security-kerberos-preauth-fail-4771", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4771 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "Kerberos 預先驗證失敗 (4771)；單日達門檻需留意密碼猜測或殘留憑證重試",
                PlainExplanation = "使用者或服務向 Active Directory 網域控制站請求 Kerberos 票證時預先驗證失敗（密碼錯誤）。在 AD 網域環境中，動態密碼(OTP)登入後未登出、隔天密碼變更造成的殘留憑證重試最典型的表現就是大量 4771，判讀時要先排除這種機械性重試再論攻擊。",
                Impact = "若為惡意攻擊，可能代表攻擊者正針對特定帳號進行密碼猜測或 Kerberoasting 探測；若為憑證殘留則會造成帳號頻繁被鎖定與登入干擾。",
                LikelyCauses = new[] { "使用者或排程服務使用過期/已變更的舊密碼持續重試（最常見）",
                    "OTP 動態密碼登入後未正常登出，殘留憑證在背景定期重試",
                    "外部或內部來源對網域帳號進行密碼猜測或暴力破解攻擊",
                    "使用者時鐘與網域控制站時間偏移過大" },
                NextSteps = new[] { "確認失敗帳號、用戶端 IP 與失敗代碼（如 0x18 代表密碼錯誤、0x25 代表時鐘偏移）",
                    "先排查是否為使用者密碼變更後，手機、筆電或已連線的網路磁碟機殘留舊憑證重試",
                    "若排除殘留憑證且同一 IP 短時間內嘗試多個帳號，視為攻擊啟動來源隔離",
                    "確認帳號密碼強度並檢查該帳號近期是否有成功登入紀錄" } },
        new() { Id = "builtin-security-account-disabled-deleted-4725-4726", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4725, 4726 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "使用者帳戶被停用 (4725) 或刪除 (4726)——需確認是否為授權的管理維運操作",
                PlainExplanation = "系統上有使用者帳戶被停用或被永久刪除。非授權的帳戶刪除可能是攻擊者滅跡或阻斷服務的手法。",
                Impact = "若為正常離職或權限回收作業則屬合規；若為非預期操作，可能導致正常業務服務中斷，或為入侵者刪除足跡掩飾活動。",
                LikelyCauses = new[] { "IT 管理員正常的人員離職或帳號生命週期管理作業",
                    "自動化身分目錄同步工具執行的停用/刪除",
                    "入侵者刪除帳號滅跡或進行破壞性阻斷" },
                NextSteps = new[] { "確認執行停用/刪除的操作者帳號與異動時間點",
                    "比對 IT 工單或人員異動紀錄確認是否為授權操作",
                    "非預期刪除時立即確認受影響帳號的業務範圍並評估還原或重建",
                    "檢查該操作者帳號在同時段是否有其他異常管理行為" } },
        // 4767 刻意不設 High：殘留憑證重試會反覆鎖定帳號、helpdesk 例行解鎖是日常，High 會天天誤報。
        new() { Id = "builtin-security-account-unlocked-4767", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4767 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "使用者帳戶被解鎖 (4767)；頻繁解鎖需比對登入失敗與鎖定紀錄",
                PlainExplanation = "先前被鎖定的使用者帳戶已被管理員或自動化工具解鎖。殘留憑證重試常導致帳號反覆鎖定與解鎖，故設為 Medium 避免誤報；頻繁解鎖同一帳號時，對照該帳號的登入失敗（4625/4771）與鎖定（4740）。",
                Impact = "單次解鎖多為例行求助處理；但若帳戶剛解鎖又立即遭攻擊鎖定，或未經授權被解鎖，可能讓攻擊者得以繼續嘗試入侵。",
                LikelyCauses = new[] { "IT Helpdesk 回應使用者忘記密碼或誤打密碼的例行解鎖請求",
                    "殘留憑證導致帳號反覆鎖定後的例行解鎖",
                    "管理員或自動化自助解鎖服務執行作業",
                    "入侵者利用已取得的權限解鎖目標帳號" },
                NextSteps = new[] { "確認執行解鎖的管理員身分與解鎖原因",
                    "對照該帳號前後的登入失敗（4625/4771）與鎖定（4740）事件，評估是否遭受持續暴力破解",
                    "若同一帳號頻繁被鎖定又解鎖，協助使用者清理工作站殘留憑證與連線",
                    "非預期解鎖時立即將帳號再次停用並調查操作來源" } },
        // 4738 門檻 10 是刻意的：AD 例行同步環境單日可達數萬則；試點若仍吵，優先降嚴重度而非再拉高門檻。
        new() { Id = "builtin-security-account-modified-4738", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4738 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "使用者帳戶屬性被變更 (4738)；單日達門檻需留意批次屬性竄改或未授權異動",
                PlainExplanation = "使用者帳戶的屬性（如主目錄、登入腳本、密碼設定、帳號到期日等）被修改。AD 例行同步環境單日可達數萬則，故設定門檻 10；試點若仍吵，優先降嚴重度而非再拉高門檻。",
                Impact = "若攻擊者竄改帳號屬性（例如變更登入腳本或放寬密碼限制），可能達成權限維持或繞過安全性控制。",
                LikelyCauses = new[] { "AD 網域目錄同步服務或身分管理系統的例行屬性更新",
                    "IT 管理員正常的帳號屬性維護",
                    "入侵者修改帳號屬性（如 UserAccountControl 旗標）以利持久化或存取" },
                NextSteps = new[] { "查看變更事件的詳細欄位，確認被修改的具體屬性（如 PasswordLastSet, UserAccountControl）",
                    "確認操作者是否為已知的目錄同步服務帳號或授權管理員",
                    "若為非預期的大量屬性修改，立即比對異動內容並評估回復",
                    "檢查受異動帳號是否有密碼永不過期等高風險屬性被啟用" } },
        new() { Id = "builtin-security-scheduled-task-deleted-4699", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4699 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "排程工作被刪除 (4699)——可能為入侵者滅跡或破壞防護排程的特徵",
                PlainExplanation = "系統上的排程工作 (Scheduled Task) 被刪除。攻擊者在執行完惡意任務或為掩飾持久化足跡時，常會刪除既有的排程工作。",
                Impact = "若為防禦性排程（如備份、日誌清理、防毒掃描）被刪除，會降低系統安全防護能力；若為攻擊者刪除臨時排程則代表滅跡。",
                LikelyCauses = new[] { "管理員手動清理過期或不再需要的排程工作",
                    "軟體解除安裝程式正常移除自身的排程任務",
                    "入侵者刪除惡意排程以銷毀鑑識證據，或刪除防禦監控排程" },
                NextSteps = new[] { "確認被刪除的排程名稱、路徑與操作者帳號",
                    "確認是否為已知軟體移除或維運清理作業",
                    "非預期刪除時，對照先前是否有排程建立 (4698) 或執行紀錄，還原攻擊時間軸",
                    "檢查是否影響到系統備份或資安監控等關鍵排程工作" } },
        // 4700/4701/4702 刻意不設 High：Windows 自身維護會例行更新排程（4702 尤甚），門檻設為 5。
        new() { Id = "builtin-security-scheduled-task-lifecycle-4700-4702", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4700, 4701, 4702 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium, CountThreshold = 5,
                Description = "排程工作被啟用 (4700)、停用 (4701) 或更新 (4702)；單日達門檻需留意異常排程異動",
                PlainExplanation = "系統上的排程工作狀態或定義被變更。Windows 自身維護會例行更新排程（4702 尤甚），故設為 Medium 且門檻為 5，避免日常維護干擾。",
                Impact = "停用排程可能使安全防護或備份機制失效；更新排程動作可能是攻擊者竄改合法排程以執行惡意指令（排程劫持）。",
                LikelyCauses = new[] { "Windows 系統自動維護工作或更新程式的例行更新（4702 最常見）",
                    "管理員正常的排程維護與排程調整",
                    "軟體安裝或更新時調整既有排程",
                    "入侵者停用安全防護排程或竄改既有排程作為持久化後門" },
                NextSteps = new[] { "確認被異動的排程工作名稱與執行檔路徑",
                    "確認操作者帳號與異動時間是否對應已知的維護窗口",
                    "若是排程更新 (4702)，詳細檢查其執行的指令與參數是否有可疑腳本或路徑",
                    "非預期異動時還原排程設定並進一步排查操作來源" } },
        // 4946/4947/4948 刻意不設 High：軟體安裝與 GPO 重整會例行寫入，門檻設為 5。
        new() { Id = "builtin-security-firewall-rule-change-4946-4948", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4946, 4947, 4948 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium, CountThreshold = 5,
                Description = "Windows 防火牆規則被新增 (4946)、修改 (4947) 或刪除 (4948)；單日達門檻需留意連線邊界變更",
                PlainExplanation = "Windows 本機防火牆規則發生異動。軟體安裝、系統更新與 GPO 原則重整會例行寫入防火牆規則，故設為 Medium 且門檻為 5，避免維運雜訊。",
                Impact = "若為惡意開放通訊埠或放寬入站連線，可能讓入侵者建立外部連線通告或在內部橫向移動。",
                LikelyCauses = new[] { "合法應用程式安裝或更新時自動註冊防火牆規則",
                    "網域群組原則 (GPO) 定期重新套用或更新防火牆設定",
                    "管理員調整伺服器網路存取設定",
                    "入侵者開放特定連接埠（如 RDP/SMB）以利後續橫向移動或外連" },
                NextSteps = new[] { "檢查被異動的防火牆規則名稱、方向（入站/出站）、通訊協定與連接埠",
                    "確認操作者帳號與異動時段是否與授權軟體安裝或維運相符",
                    "若發現非預期開放高風險連接埠（如 3389, 445, 22）或允許未知程式通訊，立即移除該規則",
                    "檢查防火牆設定檔目前是否仍處於啟用狀態" } },
        new() { Id = "builtin-security-system-log-cleared-104", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "EventLog", EventIds = new[] { 104 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "System 或 Application 事件日誌被清除 (104)——入侵者滅跡的強烈訊號，應立即調查",
                PlainExplanation = "伺服器的 System、Application 或其他非 Security 事件日誌檔被清除了。對齊既有 1102（Security 清除）的語意，補上非 Security 記錄檔被清空的偵測。",
                Impact = "記錄檔被清空代表該時間點前的系統與應用程式錯誤紀錄完全遺失，嚴重阻礙故障鑑識與入侵調查。",
                LikelyCauses = new[] { "入侵者取得管理員權限後手動或以腳本清除日誌以銷毀入侵軌跡",
                    "管理員未經標準備份程序的例行清空操作",
                    "自動化維運腳本設定不當" },
                NextSteps = new[] { "立即查明執行清除日誌的操作者使用者身分與來源主機",
                    "若非已核准的維護作業，視同重大資安事件啟動應變調查程序",
                    "檢查集中式 SIEM 或外部日誌轉送伺服器是否保留了被清除前的紀錄",
                    "全面檢視該主機當前的帳號、服務、排程與網路連線狀況" } },
        // 4742（電腦帳戶變更）因機器密碼例行輪換會頻繁刷記錄，刻意不收錄。
        new() { Id = "builtin-security-computer-account-change-4741-4743", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4741, 4743 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "電腦帳戶被建立 (4741) 或刪除 (4743)；需確認是否為授權主機加入網域——4742 變更刻意不收",
                PlainExplanation = "Active Directory 網域中有新的電腦帳戶被建立，或有電腦帳戶被刪除。非預期的電腦帳戶建立可能是未授權設備（流氓機器）加入網域或委派攻擊。4742（電腦帳戶變更）因機器密碼例行輪換會頻繁觸發，刻意不收錄。",
                Impact = "若為未授權設備加入網域，攻擊者可能藉此取得網域成員身分並存取內部資源；非預期刪除則可能造成合法伺服器脫離網域中斷服務。",
                LikelyCauses = new[] { "IT 管理員正常的伺服器或工作站加入/移出網域作業",
                    "自動化主機佈署或虛擬機器範本派送",
                    "攻擊者建立流氓電腦帳戶以利用 Kerberos 限制委派或進行網域橫向移動" },
                NextSteps = new[] { "確認被建立/刪除的電腦名稱、操作者帳號與來源 IP",
                    "核對 IT 資產清冊確認該主機是否為公司合規資產",
                    "非預期建立時立即停用該電腦帳戶並隔離該實體/虛擬設備",
                    "檢查網域中一般使用者加網域配額 (ms-DS-MachineAccountQuota) 設定" } },
        new() { Id = "builtin-security-domain-group-lifecycle-4727-4758", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4727, 4730, 4754, 4758 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "全域或通用安全性群組被建立 (4727/4754) 或刪除 (4730/4758)；需確認是否為授權操作",
                PlainExplanation = "Active Directory 網域全域安全性群組 (Global Security Group) 或通用安全性群組 (Universal Security Group) 被建立或刪除。對齊本機群組 (4731/4734) 的 Medium 分級。",
                Impact = "網域群組牽涉跨主機與資源的存取控制，非預期的建立或刪除可能造成存取權限結構被竄改或業務權限中斷。",
                LikelyCauses = new[] { "網域管理員正常的組織架構調整或專案權限群組維護",
                    "身分治理系統自動化同步",
                    "入侵者建立群組以規避既有存取監控或擴大控制範圍" },
                NextSteps = new[] { "確認被建立/刪除的群組名稱、群組類型與執行者帳號",
                    "比對權限申請單確認是否為授權的管理異動",
                    "若是新建立群組，持續追蹤後續是否有帳號被加入或被賦予敏感權限",
                    "非預期異動時評估回復群組並調查執行者帳號活動" } },
        new() { Id = "builtin-security-domain-trust-kerberos-policy-4713-486x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4713, 4865, 4866, 4867 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "網域信任關係或 Kerberos 原則被變更 (4713/4865/4866/4867)——極稀有高訊號事件，應立即核實",
                PlainExplanation = "網域間的信任關係被修改 (4713)，或 Kerberos 票證原則/樹系信任被變更 (4865/4866/4867)。這是極稀有且極高訊號的網域等級架構變更。",
                Impact = "信任關係變更可能讓外部未受信任網域取得內部存取權限；Kerberos 原則變更可能降低票證安全限制，影響整個網域的驗證安全。",
                LikelyCauses = new[] { "企業跨網域整合或架構升級的授權維運（應有正式變更計畫）",
                    "入侵者建立未授權信任關係以進行跨樹系持久化後門或降級 Kerberos 防護" },
                NextSteps = new[] { "立即與網域架構主管核實是否有排程中的信任關係或原則變更作業",
                    "若無事前申請，視同最高等級資安威脅立即啟動應變與鑑識",
                    "檢查變更內容（哪個信任關係、SID 篩選是否被關閉、Kerberos 票證存活時間）",
                    "全面稽查所有網域控制站的管理員登入與異動紀錄" } },
        new() { Id = "builtin-security-dsrm-password-attempt-4794", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4794 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "目錄服務還原模式 (DSRM) 管理員密碼重設嘗試 (4794)——DC 專屬極稀有事件，需立即調查",
                PlainExplanation = "有人嘗試在網域控制站上設定或重設目錄服務還原模式 (Directory Services Restore Mode, DSRM) 的管理員密碼。此事件極少在例行維運中發生。",
                Impact = "DSRM 帳戶是 DC 本機的後門管理員帳戶；攻擊者常利用 DSRM 帳戶作為網域控制站上的持久化立足點，甚至透過 pass-the-hash 登入 DC。",
                LikelyCauses = new[] { "網域控制站災難還原演練或授權維護作業",
                    "入侵者已取得 DC 本機或網域管理權限，意圖重設 DSRM 密碼建立隱蔽持久化後門" },
                NextSteps = new[] { "立即聯繫網域管理團隊確認是否正在進行 DSRM 相關維護或演練",
                    "非預期操作時視為 DC 遭入侵事件，立即對該網域控制站啟動緊急應變",
                    "檢查操作者帳號來源、當前連線狀態及近期在 DC 上的所有活動",
                    "檢查登錄機碼中 DSRM 登入行為設定 (DsrmAdminLogonBehavior) 是否被竄改" } },
        new() { Id = "builtin-storage-ntfs-delayed-write-137", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Ntfs", EventIds = new[] { 137 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "NTFS 延遲寫入失敗 (137)；單日 ≥3 次代表儲存子系統或快取寫入不穩定",
                PlainExplanation = "NTFS 檔案系統在嘗試將記憶體快取中的資料寫入磁碟時失敗，部分資料可能遺失或未能成功儲存。",
                Impact = "延遲寫入失敗會導致應用程式資料損毀、檔案內容不完整，頻繁發生代表底層儲存硬體或控制器存在嚴重瓶頸或通訊故障。",
                LikelyCauses = new[] { "儲存硬體（硬碟、SSD 或 SAN/NAS 儲存陣列）回應逾時或壞軌",
                    "SATA/SAS 線材、HBA 卡或控制器驅動程式不穩定",
                    "網路儲存 (iSCSI/SMB) 連線短暫中斷",
                    "系統記憶體異常或快取排程負載過重" },
                NextSteps = new[] { "立即確認該磁碟區上的關鍵資料與資料庫是否完整，必要時執行檢查",
                    "檢查磁碟 S.M.A.R.T. 健康狀態與儲存控制器事件日誌",
                    "確認網路儲存連線或本機儲存排線與電源連接穩固",
                    "若反覆發生，安排排程執行 chkdsk 並準備更換故障儲存硬體" } },
        new() { Id = "builtin-hardware-bugcheck-1001", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "BugCheck", EventIds = new[] { 1001 },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "系統藍屏當機重開 (BSOD BugCheck 1001)，需分析傾印檔案找出崩潰驅動或硬體",
                PlainExplanation = "伺服器發生嚴重的核心層級崩潰（藍屏當機 BSOD），系統已自動重新開機並記錄了錯誤檢查代碼。",
                Impact = "伺服器無預警中斷重啟，正在處理中的連線與資料將直接中斷，重複當機會嚴重損害系統可靠性與業務連續性。",
                LikelyCauses = new[] { "核心層級驅動程式（顯示卡、網卡、儲存控制器、防毒軟體過濾驅動）錯誤",
                    "實體記憶體 (RAM) 模組損毀或接觸不良",
                    "CPU 過熱、供電異常或主機板硬體故障",
                    "最近安裝的系統更新或驅動程式與硬體不相容" },
                NextSteps = new[] { "記錄 BugCheck 代碼與參數（如 0x000000D1, 0x0000003B 等），查詢具體崩潰原因",
                    "使用 WinDbg 分析 C:\\Windows\\Minidump 記憶體傾印檔案，找出引起崩潰的驅動程式 (.sys)",
                    "檢查伺服器機房溫度、電源與記憶體健康狀態",
                    "若為剛更新驅動後發生，考慮回復至上一個穩定版本驅動" } },
        new() { Id = "builtin-storage-mssql-io-error-823-825", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "MSSQL", EventIds = new[] { 823, 824, 825 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "SQL Server 偵測到實體 I/O 或檢查碼錯誤 (823/824/825)——磁碟劣化的強烈訊號",
                PlainExplanation = "Microsoft SQL Server 在讀寫資料庫檔案時遇到作業系統 I/O 錯誤 (823)、邏輯一致性檢查碼錯誤 (824)，或經重試後才成功的 I/O 警告 (825)。這是底層儲存硬體劣化的強訊號。",
                Impact = "資料庫分頁可能已實體損毀，若不及時處置將導致資料庫無法掛載、查詢報錯中斷，甚至永久性資料遺失。",
                LikelyCauses = new[] { "底層磁碟機存在實體壞軌或控制器通訊錯誤",
                    "SAN/NAS 儲存網路或磁碟陣列控制器快取異常",
                    "驅動程式或韌體層級在寫入磁碟時發生損毀（Torn Page）",
                    "伺服器非預期斷電導致分頁寫入不完整" },
                NextSteps = new[] { "立即執行 DBCC CHECKDB 確認資料庫的一致性與受損範圍",
                    "確認資料庫最新備份是否完整且可正常還原，必要時立即執行完整備份與記錄備份",
                    "檢查作業系統 System 記錄檔中的磁碟與儲存控制器錯誤（如 disk 153, storahci 129）",
                    "聯絡硬體與儲存廠商排查磁碟機陣列健康並規劃更換受損磁碟" } },
        // 467/474 刻意不設重大：Windows Update 儲存庫損毀等非磁碟成因也會觸發。
        new() { Id = "builtin-storage-esent-database-corruption-467-474", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "ESENT", EventIds = new[] { 467, 474 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High,
                Description = "ESENT 資料庫分頁損毀或檢查碼錯誤 (467/474)；刻意不設重大（包含 Windows Update 等非磁碟損毀）",
                PlainExplanation = "可延伸儲存引擎 (ESENT / Jet Blue) 偵測到資料庫分頁損毀或讀取驗證檢查碼不符。AD 目錄庫 (ntds.dit)、憑證服務、Windows Update 資料庫等皆使用此引擎。刻意不設重大是因為 Windows Update 儲存庫損毀等非磁碟成因也會觸發。",
                Impact = "依賴該 ESENT 資料庫的服務（如 Windows Update、Active Directory、Exchange 或特定應用程式）可能無法正常讀寫或啟動。",
                LikelyCauses = new[] { "底層磁碟壞軌或儲存子系統讀寫錯誤",
                    "系統非預期斷電或當機導致資料庫寫入中斷",
                    "Windows Update 軟體發佈資料庫 (DataStore) 結構異常",
                    "防毒軟體或第三方備份工具鎖定資料庫檔案干擾寫入" },
                NextSteps = new[] { "查看事件內容確認是哪個資料庫檔案（.edb）發生錯誤",
                    "若為 Windows Update 資料庫，可透過重設 SoftwareDistribution 資料夾修復",
                    "若為 Active Directory (NTDS) 或 Exchange，需立即檢查磁碟健康並評估資料庫還原或離線修復 (esentutl)",
                    "檢查 System 日誌是否有底層磁碟 I/O 相關錯誤" } },
        new() { Id = "builtin-service-app-hang-1002", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Application Hang", EventIds = new[] { 1002 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "應用程式停止回應 (Application Hang 1002)；單日 ≥3 次需檢查死結或外部相依逾時",
                PlainExplanation = "某個應用程式停止回應與系統的互動（凍結/無回應），補齊既有 Application Error (1000) 應用程式崩潰的另一半面向。",
                Impact = "應用程式無回應會導致使用者操作中斷、批次作業停擺，通常需強制結束程序才能恢復，可能造成處理中資料遺失。",
                LikelyCauses = new[] { "應用程式內部執行緒發生死結 (deadlock) 或進入無窮迴圈",
                    "應用程式存取外部資源（資料庫、網路共用、API）發生嚴重逾時阻塞 UI/主執行緒",
                    "系統資源（CPU/記憶體/磁碟 I/O）極度繁忙導致應用程式無法及時處理訊息",
                    "第三方外掛程式或防毒過濾模組相容性問題" },
                NextSteps = new[] { "確認經常無回應的程式名稱、模組與發生時間點",
                    "檢查無回應時伺服器的 CPU、記憶體與磁碟 I/O 負載狀況",
                    "確認該程式連線的後端資料庫或相依網路服務是否正常且回應迅速",
                    "若為自行開發系統，將當結報告提供開發團隊分析執行緒鎖定與逾時邏輯" } },

        // ── Linux（docs/LINUX-RULES.md，seed v4）──────────────────────
        // 比對走 Platform="linux" 的 ProgramPattern＋MessagePatterns 路（EventNamePattern 留空，
        // 待 NetIQ 診斷分頁的 probe 在真實環境確認 Sentinel 有無做事件正規化後補上，見規劃文件 §1.2/§8）。
        // ProgramPattern 沿用 SourcePattern 同樣的 Contains 語意，因此同一規則只精準對應
        // 一個實際的 syslog identifier（不像規劃草案表格把 su／sudo、chronyd／ntpd 等不同程式
        // 併成一列）——分成獨立規則，避免用寬鬆子字串（如 "su"）意外命中不相關的程式名稱。
        new() { Id = "builtin-linux-ssh-bruteforce", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "sshd", MessagePatterns = new[] { "Failed password", "authentication failure", "Invalid user" },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "SSH 登入失敗；單日達門檻視為暴力破解攻擊",
                PlainExplanation = "有人反覆嘗試以錯誤密碼或不存在的帳號登入這台主機的 SSH 服務。",
                Impact = "持續嘗試可能猜中弱密碼而入侵成功；即使未得手也會消耗系統資源、掩蓋其他登入紀錄。",
                LikelyCauses = new[] { "網路上的自動化掃描/暴力破解攻擊（最常見）", "忘記密碼的合法使用者反覆嘗試",
                    "自動化腳本或排程任務憑證設定錯誤而反覆重試" },
                NextSteps = new[] { "確認來源 IP 是否為已知合法來源，非法來源應加入防火牆封鎖",
                    "檢查是否已啟用 fail2ban 或等效的自動封鎖機制", "考慮改用金鑰驗證並停用密碼登入",
                    "確認相同帳號/IP 是否有後續成功登入（見【破解得手】關聯）" } },
        new() { Id = "builtin-linux-ssh-accept", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "sshd", MessagePatterns = new[] { "Accepted password", "Accepted publickey" },
                Category = IssueCategory.Security, Severity = IssueSeverity.Low,
                Description = "SSH 登入成功——正常遠端維運即會產生，收集供關聯與趨勢分析，本身非告警",
                PlainExplanation = "有人成功以密碼或金鑰登入這台主機的 SSH 服務。日常遠端維運會正常產生此紀錄。",
                Impact = "單筆事件屬正常運作；只有在與同帳號/IP 的大量登入失敗交集時，才代表暴力破解可能已得手。",
                LikelyCauses = new[] { "管理員或使用者的正常 SSH 連線", "自動化工具或跳板機的遠端連線" },
                NextSteps = new[] { "正常情況無需處理", "僅在與大量登入失敗的帳號/IP 相符時才需視為破解得手調查" } },
        // fail2ban 是 Low、收集用（比照既有的 builtin-linux-ssh-accept）：確認攻擊被擋下，與 ssh 暴力破解規則互為佐證；對外主機日常有量，Low 才不會吵。
        new() { Id = "builtin-linux-security-fail2ban-ban", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "fail2ban", MessagePatterns = new[] { "Ban " },
                Category = IssueCategory.Security, Severity = IssueSeverity.Low,
                Description = "fail2ban 封鎖惡意來源 IP——收集用低嚴重度，供攻擊防護佐證，非告警",
                PlainExplanation = "fail2ban 偵測到多次認證失敗並自動將可疑來源 IP 加入防火牆封鎖清單。設為 Low 作為收集用途（比照 builtin-linux-ssh-accept）：確認攻擊已被防護機制阻擋，並與 SSH 暴力破解規則互為佐證；對外主機日常有量，Low 才不會產生干擾告警。",
                Impact = "代表系統防禦機制正常運作中，成功阻擋了外部暴力破解或掃描嘗試。",
                LikelyCauses = new[] { "網際網路上自動化掃描器對 SSH 或 Web 服務發動暴力破解被 fail2ban 攔截",
                    "合法使用者多次打錯密碼觸發防禦封鎖" },
                NextSteps = new[] { "正常情況無需處理", "防護機制已自動生效",
                    "若需確認受阻擋 IP 清單，可執行 fail2ban-client status <jail>",
                    "若為合法使用者誤觸封鎖，可手動執行 fail2ban-client set <jail> unbanip <IP> 解鎖" } },
        // sudo 必須排在 su 前面：ProgramPattern 是子字串比對，"sudo" 天然包含 "su"，
        // su 規則排在前面會讓 sudo 的事件被 su 規則先攔截（selftest 曾抓到這個問題）。
        new() { Id = "builtin-linux-sudo-auth-failure", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "sudo", MessagePatterns = new[] { "authentication failure", "incorrect password attempt" },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium, CountThreshold = 5,
                Description = "sudo 提權密碼驗證失敗；短時間內反覆出現可能是提權嘗試",
                PlainExplanation = "有人在這台主機上以 sudo 執行需要管理員權限的指令，但密碼驗證失敗。",
                Impact = "偶發多為手誤；反覆出現代表有帳號在嘗試取得管理員權限但驗證失敗。",
                LikelyCauses = new[] { "使用者忘記自己的密碼手誤輸入", "已登入帳號的攻擊者嘗試提權執行特權指令" },
                NextSteps = new[] { "確認執行者身分、指令內容與時段是否合理", "反覆失敗應追查該帳號的登入來源",
                    "檢查 sudoers 設定是否過於寬鬆" } },
        new() { Id = "builtin-linux-su-auth-failure", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "su", MessagePatterns = new[] { "authentication failure", "incorrect password", "FAILED su" },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium, CountThreshold = 5,
                Description = "su 提權密碼驗證失敗；短時間內反覆出現可能是提權嘗試",
                PlainExplanation = "有人在這台主機上嘗試切換到其他帳號（常見是切到 root）但密碼輸入錯誤。",
                Impact = "偶發多為手誤；反覆出現代表有人在嘗試取得更高權限但驗證失敗。",
                LikelyCauses = new[] { "使用者忘記密碼手誤輸入", "已登入帳號的攻擊者嘗試提權至 root 或其他帳號" },
                NextSteps = new[] { "確認執行者身分與時段是否合理", "反覆失敗應追查來源工作階段的登入紀錄",
                    "確認 root 密碼未外洩、必要時更換" } },
        new() { Id = "builtin-linux-account-change", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "useradd",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳號建立（useradd）— 入侵者建立立足點的典型手法，也收錄管理員的正常維運",
                PlainExplanation = "系統帳號被建立。管理員的正常維運與入侵者建立後門帳號都會產生這類紀錄，需要人工判斷合理性。",
                Impact = "非預期的帳號建立可能代表入侵者已建立可重複進入的後門帳號。",
                LikelyCauses = new[] { "管理員的正常主機維運（新進人員等）", "自動化佈署工具建立服務帳號",
                    "入侵者建立後門帳號以維持存取權限" },
                NextSteps = new[] { "確認異動是否為已知的維運操作", "非預期的帳號應立即停用並調查建立來源",
                    "檢查新帳號是否被加入特權群組（見【priv-group-membership】）" } },
        new() { Id = "builtin-linux-account-mod", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "usermod",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳號修改（usermod）— 帳號設定或群組隸屬異動，需確認授權",
                PlainExplanation = "系統帳號的屬性、密碼狀態或附屬群組被修改。需確認是否為預期的管理行為。",
                Impact = "非預期的帳號修改可能代表入侵者在調整既有帳號權限或為提權鋪路。",
                LikelyCauses = new[] { "管理員調整帳號設定或群組配置", "自動化維運腳本更新使用者環境",
                    "入侵者修改既有帳號以規避限制或提升權限" },
                NextSteps = new[] { "確認異動內容（修改了哪些屬性或群組）與執行者是否合理",
                    "非預期異動應立即還原並調查操作來源", "檢查該帳號近期的其他活動" } },
        new() { Id = "builtin-linux-account-del", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "userdel",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳號刪除（userdel）— 帳號被自系統移除，需確認授權與滅跡可能",
                PlainExplanation = "系統帳號被刪除。除了正常的離職或帳號回收外，也需留意入侵者滅跡或破壞性行為。",
                Impact = "非預期的帳號刪除可能影響服務運作，或為攻擊者在完成操作後刪除臨時帳號以掩蓋行蹤。",
                LikelyCauses = new[] { "管理員正常回收不再使用的帳號", "自動化腳本清理臨時使用者",
                    "入侵者刪除臨時建立的攻擊帳號以滅跡" },
                NextSteps = new[] { "確認是否為已核准的帳號下線或回收程序",
                    "非預期刪除時檢查被刪除帳號先前的活動紀錄", "確認是否有相依服務受到影響" } },
        new() { Id = "builtin-linux-group-mgmt", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "groupadd",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "群組建立（groupadd）— 收錄群組建立供人工核對，需確認是否為授權操作",
                PlainExplanation = "系統群組被建立。管理員建立新權限群組或應用程式安裝時會產生此紀錄。",
                Impact = "群組建立本身影響有限，但若後續被賦予特權或加入帳號，可能改變權限邊界。",
                LikelyCauses = new[] { "管理員的正常群組維運", "應用程式或套件安裝時建立專用群組",
                    "入侵者建立自訂群組以利權限管理" },
                NextSteps = new[] { "確認是否為已知的群組維運或軟體安裝作業", "檢查新群組後續被賦予的檔案或 sudo 權限" } },
        new() { Id = "builtin-linux-group-mod", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "groupmod",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "群組修改（groupmod）— 群組名稱或 GID 變更，需確認授權",
                PlainExplanation = "系統群組的名稱或 GID 被修改。",
                Impact = "非預期的群組修改可能影響該群組成員的檔案存取權限或造成權限對應異常。",
                LikelyCauses = new[] { "管理員調整群組設定或整合目錄服務",
                    "入侵者變更群組屬性以製造混淆或存取漏洞" },
                NextSteps = new[] { "確認變更內容與執行者是否合理",
                    "非預期異動應立即調查並檢查相關檔案權限" } },
        new() { Id = "builtin-linux-group-del", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "groupdel",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "群組刪除（groupdel）— 群組被自系統移除，需確認授權",
                PlainExplanation = "系統群組被刪除。需確認是否為預期的退場作業或攻擊者破壞。",
                Impact = "群組刪除可能導致依賴該群組的服務或使用者無法正常存取資源。",
                LikelyCauses = new[] { "管理員正常清理不再使用的群組",
                    "入侵者破壞性操作或刪除臨時群組以滅跡" },
                NextSteps = new[] { "確認是否為已核准的群組回收程序",
                    "檢查是否有相依服務或檔案存取因此異常" } },
        new() { Id = "builtin-linux-priv-group-membership", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "gpasswd",
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳號被加入/移出群組（gpasswd）— 常見於加入 sudo/wheel 等特權群組的提權手法",
                PlainExplanation = "有帳號被加入或移出某個群組，最需要留意的是加入 sudo、wheel 這類擁有管理員權限的群組。",
                Impact = "非預期地把帳號加入特權群組，等同賦予該帳號管理員權限——典型提權手法。",
                LikelyCauses = new[] { "管理員的正常權限指派", "入侵者把已入侵帳號加入特權群組以取得管理員權限" },
                NextSteps = new[] { "確認異動的帳號、目標群組與執行者是否合理", "非預期加入特權群組應立即移出並調查",
                    "檢查該帳號近期是否有異常登入活動" } },
        new() { Id = "builtin-linux-audit-tamper", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "auditd", MessagePatterns = new[] { "audit daemon is exiting", "The audit daemon is stopping" },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "auditd 稽核服務被停止 — 入侵者滅跡的典型行為，應立即調查",
                PlainExplanation = "系統的稽核記錄服務被關閉，關閉後續的操作將不會被記錄下來。",
                Impact = "稽核服務關閉期間發生的任何操作都不會留下紀錄，是入侵者掩蓋行蹤的常見手法。",
                LikelyCauses = new[] { "管理員的計畫性維護（應有變更紀錄可查）", "入侵者取得權限後關閉稽核以躲避偵測" },
                NextSteps = new[] { "立即確認是否為已排程的維護操作", "非計畫性關閉應視為高度可疑，立即調查該時段的其他活動",
                    "確認 auditd 已重新啟用並檢查設定是否被竄改" } },
        // crontab 編輯＝排程持久化，對齊 Windows 4698 的語意。
        new() { Id = "builtin-linux-security-crontab-edit", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "crontab", MessagePatterns = new[] { "REPLACE", "BEGIN EDIT" },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "使用者編輯或更新 crontab 排程任務——對齊 Windows 4698 持久化特徵",
                PlainExplanation = "有人使用 crontab 指令編輯或取代了使用者的排程任務。對齊 Windows 4698（排程建立）的語意，記錄排程持久化跡象供人工核對。",
                Impact = "合法管理員常透過 crontab 設定例行維運腳本；但攻擊者也常利用 crontab 植入反向 Shell 或惡意程式以達成持久化。",
                LikelyCauses = new[] { "系統管理員新增或修改例行備份/同步等排程任務",
                    "應用程式安裝程序建立的使用者排程",
                    "入侵者編輯 crontab 植入定時執行的惡意腳本或後門" },
                NextSteps = new[] { "檢查是哪個帳號的 crontab 被修改（如 root 或一般使用者）",
                    "檢視 /var/spool/cron/crontabs/ 中對應使用者的排程內容與執行腳本路徑",
                    "確認排程內容是否為已知的維運工作，特別留意包含 curl, wget, base64 或外部連線的指令",
                    "非預期排程應立即清除並調查該帳號近期的登入來源" } },
        // 唯讀重掛規則必須排在 storage-io 前面：當 EXT4 發生錯誤並重掛為唯讀時，優先命中更專一的 remount-ro 規則。
        new() { Id = "builtin-linux-storage-remount-ro", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "Remounting filesystem read-only", "re-mounted. Opts: ro" },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "檔案系統因錯誤被核心強制唯讀重掛 (remount read-only)——儲存故障重大警訊",
                PlainExplanation = "作業系統核心在偵測到嚴重的檔案系統結構錯誤或底層磁碟 I/O 故障時，主動將檔案系統強制重新掛載為唯讀模式以保護資料不再擴大損壞。",
                Impact = "唯讀重掛後所有需要寫入該磁碟區的服務（資料庫、日誌、Web）將全面寫入失敗中斷，系統處於半停擺狀態。",
                LikelyCauses = new[] { "底層實體磁碟發生壞軌或儲存陣列通訊中斷",
                    "檔案系統中繼資料 (metadata) 嚴重損毀",
                    "虛擬化環境下的後端儲存連線逾時中斷" },
                NextSteps = new[] { "立即確認最新備份是否完整有效",
                    "檢查 dmesg 尋找檔案系統與磁碟控制器的完整錯誤堆疊",
                    "安排在維護窗口中卸載該檔案系統並執行 fsck 修復",
                    "使用 smartctl 檢查實體磁碟健康狀況，若為硬體故障應立即更換" } },
        new() { Id = "builtin-linux-storage-io", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "I/O error", "Buffer I/O error", "EXT4-fs error", "XFS internal error" },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "磁碟 I/O 或檔案系統錯誤 — 硬碟即將故障最直接的訊號",
                PlainExplanation = "這台主機的硬碟或檔案系統出現讀寫錯誤，是硬碟即將故障最直接的警訊。",
                Impact = "繼續惡化可能導致資料損毀、檔案系統無法掛載，甚至硬碟完全故障、資料無法救回。",
                LikelyCauses = new[] { "硬碟已達使用壽命末期或有壞軌", "磁碟控制器、線材或背板接觸不良",
                    "虛擬化環境下的儲存後端異常（如 SAN/NAS 連線問題）" },
                NextSteps = new[] { "立即確認最新一次備份是否成功且可還原", "用 smartctl 檢查硬碟 S.M.A.R.T. 健康狀態",
                    "安排更換硬碟或排查儲存後端", "若為 RAID/LVM，確認其他磁碟健康、預留備援時間" } },
        new() { Id = "builtin-linux-smart-prefail", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "smartd", MessagePatterns = new[] { "Prefailure", "FAILED SMART self-check", "predicted TO FAIL" },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "S.M.A.R.T. 預警硬碟即將故障",
                PlainExplanation = "硬碟自我監控系統（S.M.A.R.T.）偵測到即將故障的跡象。",
                Impact = "硬碟可能在短期內故障，繼續使用有資料遺失風險。",
                LikelyCauses = new[] { "硬碟已達使用壽命末期", "硬碟本身存在製造瑕疵或已受損" },
                NextSteps = new[] { "立即確認最新一次備份是否成功且可還原", "盡快安排更換該硬碟",
                    "若為 RAID 陣列，確認可承受單顆磁碟失效並預留更換時間" } },
        new() { Id = "builtin-linux-storage-mdadm-degraded", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "mdadm", MessagePatterns = new[] { "DegradedArray", "Fail event", "FailSpare event" },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "Linux 軟體 RAID 陣列降級或磁碟失效 (mdadm DegradedArray/Fail)——備援能力受損",
                PlainExplanation = "Linux 軟體磁碟陣列管理服務 (mdadm) 偵測到陣列中的成員磁碟故障或陣列已處於降級 (Degraded) 狀態。",
                Impact = "陣列已失去容錯備援能力；若在修復前再有另一顆磁碟失效，將導致整個磁碟陣列損毀且資料完全遺失。",
                LikelyCauses = new[] { "陣列中某顆實體硬碟壞軌或完全故障離線",
                    "磁碟線材鬆脫或儲存控制器通道異常",
                    "熱備援磁碟 (Spare) 同步或重建失敗" },
                NextSteps = new[] { "執行 cat /proc/mdstat 與 mdadm --detail /dev/mdX 檢查陣列狀態與故障磁碟代號",
                    "確認備份是否最新且可正常還原",
                    "更換故障硬碟並執行 mdadm --manage /dev/mdX --add 加入新硬碟進行重建",
                    "監控重建進度並避免在重建期間進行高負載 I/O 操作" } },
        new() { Id = "builtin-linux-resource-disk-space", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "No space left on device" },
                Category = IssueCategory.Resource, Severity = IssueSeverity.High,
                Description = "核心回報磁碟空間耗盡 (No space left on device)",
                PlainExplanation = "作業系統核心在寫入檔案或配置磁碟區塊時回報空間不足（No space left on device）。",
                Impact = "磁碟空間耗盡會導致日誌無法寫入、資料庫無法交易、暫存檔建立失敗，甚至導致關鍵服務或系統本身停擺。",
                LikelyCauses = new[] { "日誌檔案、暫存檔或備份檔未定期清理累積佔滿磁碟",
                    "應用程式產生大量資料且未配置磁碟配額限制",
                    "磁碟的 Inode 節點耗盡（即使剩餘容量顯示充足）" },
                NextSteps = new[] { "執行 df -h 與 df -i 檢查各掛載點的容量與 Inode 使用率",
                    "找出佔用空間最大的目錄（如 /var/log, /tmp, /var/lib）進行清理",
                    "檢查是否有已刪除但仍被行程佔用 (deleted) 的大型檔案並重啟相關服務釋放空間",
                    "評估擴充磁碟容量或調整檔案生命週期政策" } },
        new() { Id = "builtin-linux-hw-netdev-down", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "Link is Down", "NETDEV WATCHDOG" },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "網路介面斷線或網卡傳輸逾時 (Link is Down / NETDEV WATCHDOG)",
                PlainExplanation = "核心偵測到實體/虛擬網路卡連線中斷 (Link is Down) 或網卡傳輸佇列逾時 (NETDEV WATCHDOG)。",
                Impact = "網路斷線或傳輸逾時會導致網路封包遺失、連線瞬斷或伺服器完全失去網路通訊能力。",
                LikelyCauses = new[] { "實體網路線接觸不良、交換器 (Switch) 連接埠重啟或故障",
                    "網卡驅動程式臭蟲或韌體異常導致傳輸佇列卡死",
                    "主機網路負載過高觸發網卡硬體緩衝區溢位" },
                NextSteps = new[] { "檢查實體網線與上層交換器連接埠狀態",
                    "使用 ethtool 檢查網卡連線速度、雙工模式與錯誤統計計數",
                    "確認網卡驅動程式與韌體是否需要更新",
                    "若反覆出現 NETDEV WATCHDOG，考慮調整網卡卸載設定 (tso/gso) 或更換網卡" } },
        new() { Id = "builtin-linux-hw-error", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "Hardware Error", "Machine Check", "mce: [Hardware Error]" },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High, ElevatesDayRisk = true,
                Description = "硬體層級錯誤（CPU/記憶體/PCIe）；corrected error 次數上升是硬體劣化的典型前兆",
                PlainExplanation = "CPU、記憶體或 PCIe 匯流排偵測到硬體層級的錯誤，這是硬體開始劣化的訊號。",
                Impact = "可修正錯誤持續累積代表硬體正在劣化，若演變成不可修正錯誤可能直接導致當機或資料損毀。",
                LikelyCauses = new[] { "記憶體模組故障或接觸不良", "CPU 過熱或供電不穩", "主機板或 PCIe 裝置異常" },
                NextSteps = new[] { "記錄錯誤發生頻率與趨勢，確認是否持續上升", "安排硬體診斷（記憶體測試、溫度監控）",
                    "頻率持續上升時，安排在下個維護窗口更換可疑硬體元件" } },
        new() { Id = "builtin-linux-oom-kill", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "Out of memory", "oom-kill", "Killed process" },
                Category = IssueCategory.Resource, Severity = IssueSeverity.High,
                Description = "記憶體耗盡，核心強制終止程序（OOM killer）",
                PlainExplanation = "這台主機的記憶體用盡，作業系統核心被迫強制關閉某個程序來釋放記憶體。",
                Impact = "被強制終止的程序若是服務行程，會直接造成服務中斷；反覆發生代表記憶體持續不足。",
                LikelyCauses = new[] { "應用程式記憶體洩漏", "同時運行的服務記憶體需求超過主機配置",
                    "單一異常請求或批次作業瞬間耗用大量記憶體" },
                NextSteps = new[] { "確認被終止的程序是哪個服務，檢查該服務是否需要重啟",
                    "檢查是否有記憶體洩漏跡象（持續攀升的用量趨勢）", "評估是否需要增加記憶體或調整服務的資源限制" } },
        new() { Id = "builtin-linux-service-fail-loop", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "systemd", MessagePatterns = new[] { "entered failed state", "Failed to start", "Main process exited" },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "systemd 服務啟動失敗或異常終止；單日 ≥3 次才升為 Medium（偶發屬正常雜訊）",
                PlainExplanation = "某個系統服務未能正常啟動，或啟動後異常終止進入失敗狀態。",
                Impact = "反覆失敗代表該服務完全無法提供功能，可能導致依賴它的其他服務或應用一併受影響。",
                LikelyCauses = new[] { "服務設定檔錯誤或相依服務未就緒", "服務本身的程式錯誤或資源不足（記憶體/檔案控制代碼）",
                    "近期系統更新或設定變更造成相容性問題" },
                NextSteps = new[] { "用 systemctl status 與 journalctl -u 查看該服務詳細錯誤",
                    "確認相依服務（資料庫、網路等）是否正常", "近期若有更新或改設定，考慮是否需要回復" } },
        new() { Id = "builtin-linux-segfault", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "kernel", MessagePatterns = new[] { "segfault" },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "應用程式反覆區段錯誤（segfault）；單日 ≥3 次才升為 Medium",
                PlainExplanation = "某個應用程式發生記憶體存取錯誤而被系統強制終止。",
                Impact = "偶發多為程式本身的錯誤；反覆發生代表該服務不穩定，可能影響其提供的功能。",
                LikelyCauses = new[] { "應用程式本身有臭蟲（memory corruption 等）", "程式版本與系統函式庫不相容",
                    "硬體記憶體問題（可與 WHEA/Machine Check 訊號對照）" },
                NextSteps = new[] { "確認是哪個程式反覆發生，檢查是否有已知的版本問題",
                    "檢視該程式的 core dump 或錯誤紀錄協助定位", "若近期無變更卻突然頻繁發生，留意是否為硬體記憶體問題" } },
        // rsyslog 掉訊息＝監控盲區（log 遺失會讓其他偵測失效）。
        new() { Id = "builtin-linux-config-rsyslog-drop", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "rsyslogd", MessagePatterns = new[] { "begin to drop messages", "suspended" },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "rsyslog 訊息丟棄或動作暫停 (drop messages/suspended)——監控盲區風險",
                PlainExplanation = "rsyslog 記錄服務因訊息量過大超過處理速率而開始丟棄日誌訊息，或因遠端轉送目的地無回應而暫停動作。日誌遺失會造成資安與維運監控盲區。",
                Impact = "日誌遺失期間發生的系統錯誤或資安攻擊將無法被記錄與偵測，嚴重破壞稽核完整性與鑑識能力。",
                LikelyCauses = new[] { "某個服務在短時間內爆發海量日誌（日誌風暴）塞爆 rsyslog 緩衝佇列",
                    "遠端日誌伺服器 (SIEM/Syslog Server) 網路中斷或伺服器離線",
                    "rsyslog 輸出通道磁碟空間已滿無法寫入" },
                NextSteps = new[] { "確認是本機日誌佇列溢位還是遠端轉送目標連線失敗",
                    "找出正在大量輸出日誌的異常服務並修復該服務根因或調整其日誌等級",
                    "確認遠端日誌伺服器的網路連線與負載狀態",
                    "評估調整 /etc/rsyslog.conf 中的佇列大小與磁碟緩衝設定" } },
        new() { Id = "builtin-linux-time-sync-chrony", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "chronyd", MessagePatterns = new[] { "Can't synchronise", "no reachable sources" },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "chrony 時間同步失敗；單日 ≥3 次才升為 Medium",
                PlainExplanation = "這台主機的系統時間無法與時間伺服器同步。",
                Impact = "時鐘偏移過大會導致 Kerberos 驗證失敗、憑證驗證異常、日誌時間軸錯亂難以比對事件先後。",
                LikelyCauses = new[] { "網路無法連上設定的時間伺服器", "時間伺服器設定錯誤或已停用",
                    "防火牆封鎖 NTP（UDP 123）流量" },
                NextSteps = new[] { "確認能否連上設定的時間伺服器", "檢查防火牆是否放行 NTP 流量",
                    "偏移過大時考慮手動校時後再讓服務接手同步" } },
        new() { Id = "builtin-linux-time-sync-ntp", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "ntpd", MessagePatterns = new[] { "time reset", "synchronisation lost", "no servers reachable" },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "ntpd 時間同步失敗；單日 ≥3 次才升為 Medium",
                PlainExplanation = "這台主機的系統時間無法與時間伺服器同步。",
                Impact = "時鐘偏移過大會導致 Kerberos 驗證失敗、憑證驗證異常、日誌時間軸錯亂難以比對事件先後。",
                LikelyCauses = new[] { "網路無法連上設定的時間伺服器", "時間伺服器設定錯誤或已停用",
                    "防火牆封鎖 NTP（UDP 123）流量" },
                NextSteps = new[] { "確認能否連上設定的時間伺服器", "檢查防火牆是否放行 NTP 流量",
                    "偏移過大時考慮手動校時後再讓服務接手同步" } },
        new() { Id = "builtin-linux-cron-failure", Origin = "builtin", Enabled = true, Scope = "all", Platform = "linux",
                ProgramPattern = "CRON", MessagePatterns = new[] { "FAILED", "(CRON) ERROR" },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "排程任務（cron）執行失敗；單日 ≥3 次才升為 Medium",
                PlainExplanation = "系統排程任務（cron job）執行失敗。",
                Impact = "依賴排程任務的作業（備份、清理、同步等）可能因此沒有執行，累積下來影響更大。",
                LikelyCauses = new[] { "排程腳本本身有錯誤或相依條件未滿足", "腳本執行權限或路徑設定錯誤",
                    "系統資源不足導致腳本執行逾時" },
                NextSteps = new[] { "檢查 /var/log/cron 或對應日誌找出是哪個排程任務失敗",
                    "手動執行該腳本確認錯誤原因", "確認該排程任務的重要性，評估是否需要立即補跑" } },
    };
}
