namespace LogForesight;

/// <summary>
/// 內建規則種子：初次部署時寫入外部儲存（rules.json，未來 DB）的起始內容，也是
/// <see cref="KnownIssueCatalog.Rules"/> 在未呼叫 Initialize 前的預設值（單元測試/selftest 降級路徑）。
/// 這裡不再是唯一的規則來源——使用者可在 rules.json 停用/新增規則；`--import-rules` 用
/// <see cref="Version"/> 判斷是否有新版種子內容可匯入。Id 一經出貨永不改名（見 docs/RULES-PLAN.md）。
/// </summary>
public static class KnownIssueSeed
{
    /// <summary>種子版本：每次調整 CreateRules() 的內容（新增規則、修訂知識庫文字）就遞增，
    /// `--import-rules` 依此判斷 rules.json 是否落後於程式內建的種子。</summary>
    public const int Version = 1;

    public static List<KnownIssueRule> CreateRules() => new()
    {
        // ── 儲存裝置（硬碟故障最重要的前兆訊號）─────────────────────────
        new() { Id = "builtin-storage-disk-io", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "disk", EventIds = new[] { 7, 11, 51, 52, 153 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.Critical,
                Description = "磁碟 I/O 錯誤或壞軌前兆，硬碟可能即將故障，應盡快備份並安排更換",
                PlainExplanation = "這台伺服器的硬碟出現讀寫錯誤，是硬碟即將故障最直接的警訊。",
                Impact = "硬碟繼續惡化可能導致資料損毀、系統當機，甚至硬碟完全故障、資料無法救回。",
                LikelyCauses = new[] { "硬碟已達使用壽命末期（機械硬碟常見，SSD 也有寫入壽命問題）",
                    "硬碟本身有壞軌或韌體異常", "SATA/SAS 線材接觸不良或控制器異常" },
                NextSteps = new[] { "立即確認最新一次備份是否成功且可還原",
                    "用廠商工具（如 CrystalDiskInfo、smartctl）檢查硬碟 S.M.A.R.T. 健康狀態",
                    "安排更換硬碟，優先順序視錯誤頻率而定", "若為 RAID 陣列，確認其他磁碟健康、預留備援時間" } },
        new() { Id = "builtin-storage-ntfs-corruption", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Ntfs", EventIds = new[] { 55, 98, 130, 140, 141 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.Critical,
                Description = "NTFS 檔案系統損毀跡象，需執行 chkdsk 並檢查底層磁碟健康",
                PlainExplanation = "檔案系統本身的結構出現異常，代表磁碟上的資料組織方式可能已經受損。",
                Impact = "檔案系統損毀若持續惡化，可能造成檔案讀取錯誤、資料遺失，甚至系統無法開機。",
                LikelyCauses = new[] { "底層磁碟硬體故障（壞軌）", "非預期斷電或當機造成寫入中斷",
                    "磁碟機或控制器驅動程式問題" },
                NextSteps = new[] { "盡快排程執行 chkdsk /f 修復（需重開機或於維護時段執行）",
                    "chkdsk 前務必先確認備份", "同步檢查磁碟硬體健康狀況（見磁碟 I/O 錯誤處置）",
                    "若同一顆磁碟反覆出現，優先考慮更換硬體而非只修復檔案系統" } },
        new() { Id = "builtin-storage-controller-timeout", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "stor", EventIds = new[] { 129 },
                Category = IssueCategory.Storage, Severity = IssueSeverity.High,
                Description = "儲存控制器逾時重置 (storahci/stornvme 129)，常見於硬碟劣化、線材或背板異常",
                PlainExplanation = "儲存控制器對磁碟的指令逾時、自動重置連線，代表磁碟或連接路徑不穩定。",
                Impact = "偶發不一定立即造成問題，但頻繁發生代表儲存路徑劣化中，可能演變成磁碟離線或資料存取失敗。",
                LikelyCauses = new[] { "硬碟本身開始劣化", "SATA/SAS 線材或背板接觸不良",
                    "儲存控制器韌體或驅動程式問題", "磁碟陣列電源供應不穩" },
                NextSteps = new[] { "檢查該磁碟槽位的線材與背板連接", "確認控制器與磁碟韌體/驅動為最新版本",
                    "留意是否與磁碟 I/O 錯誤（Event 153 等）同時出現，若有代表故障已進入下一階段",
                    "持續發生應排查硬體或安排更換" } },
        new() { Id = "builtin-resource-disk-space-low", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "srv", EventIds = new[] { 2013 },
                Category = IssueCategory.Resource, Severity = IssueSeverity.Medium,
                Description = "磁碟空間即將不足",
                PlainExplanation = "系統偵測到磁碟剩餘空間即將用盡。",
                Impact = "空間耗盡後，服務可能因無法寫入暫存/日誌檔而異常，甚至系統本身無法正常運作。",
                LikelyCauses = new[] { "日誌檔、暫存檔或備份檔案持續累積未清理", "應用程式產生大量資料未歸檔",
                    "磁碟配置容量原本就偏小" },
                NextSteps = new[] { "立即檢查磁碟使用狀況，找出佔用空間最大的目錄",
                    "清理不需要的暫存檔/舊日誌/舊備份", "評估是否需要擴充磁碟容量或搬移資料" } },

        // ── 硬體（CPU / 記憶體 / 電源）───────────────────────────────
        new() { Id = "builtin-hardware-whea-error", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "WHEA-Logger",
                Category = IssueCategory.Hardware, Severity = IssueSeverity.Critical,
                Description = "WHEA 硬體錯誤 (CPU/記憶體/PCIe)。corrected error 次數上升是硬體劣化的典型前兆",
                PlainExplanation = "CPU、記憶體或 PCIe 匯流排偵測到硬體層級的錯誤，這是硬體開始劣化的訊號。",
                Impact = "corrected error（可修正錯誤）持續累積代表硬體正在劣化，若演變成 uncorrected error 可能直接導致當機或資料損毀。",
                LikelyCauses = new[] { "記憶體模組故障或接觸不良", "CPU 過熱或供電不穩",
                    "主機板或 PCIe 裝置（如網卡、擴充卡）異常", "機房環境溫濕度異常" },
                NextSteps = new[] { "記錄錯誤發生頻率與趨勢，確認是否持續上升",
                    "檢查主機板 BIOS/韌體是否為最新版本", "安排硬體診斷（記憶體測試、CPU 溫度監控）",
                    "頻率持續上升時，安排在下個維護窗口更換可疑硬體元件" } },
        new() { Id = "builtin-hardware-kernel-power-41", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Kernel-Power", EventIds = new[] { 41 },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.Critical,
                Description = "非預期斷電或當機重開 (Kernel-Power 41)，可能為電源、過熱或硬體不穩",
                PlainExplanation = "系統沒有正常關機程序就重新啟動了，通常代表突發斷電、當機或硬體異常。",
                Impact = "重複發生代表電源、散熱或硬體有間歇性問題，可能導致資料未寫入完成而損毀，或演變成更嚴重的當機。",
                LikelyCauses = new[] { "電源供應器（PSU）故障或不穩", "UPS 異常或未正確供電",
                    "硬體過熱自動保護關機", "驅動程式或核心層級當機" },
                NextSteps = new[] { "檢查該時間點的電力紀錄與 UPS 日誌", "確認機房溫度與伺服器散熱狀況",
                    "檢查電源供應器健康狀態", "若排除電力因素，安排硬體診斷排查主機板/記憶體/CPU" } },
        new() { Id = "builtin-hardware-unexpected-shutdown-6008", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "EventLog", EventIds = new[] { 6008 },
                Category = IssueCategory.Hardware, Severity = IssueSeverity.High,
                Description = "非預期關機",
                PlainExplanation = "系統前一次關機沒有走正常程序，等於是非計劃性的停機。",
                Impact = "偶發可能只是人為誤觸或短暫斷電；頻繁發生則代表系統穩定性有問題。",
                LikelyCauses = new[] { "斷電或電力不穩", "系統當機後自動或被迫重開", "人員未依正常程序關機" },
                NextSteps = new[] { "對照 Kernel-Power 41 等相關事件，確認是否為同一次事件的不同紀錄",
                    "檢查電力與 UPS 狀況", "頻繁發生時視同硬體不穩處理，排查電源與散熱" } },
        new() { Id = "builtin-resource-exhaustion", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "Resource-Exhaustion",
                Category = IssueCategory.Resource, Severity = IssueSeverity.High,
                Description = "系統資源（虛擬記憶體）即將耗盡，可能有程式記憶體洩漏",
                PlainExplanation = "系統的虛擬記憶體（分頁檔）即將用盡。",
                Impact = "虛擬記憶體耗盡會導致應用程式配置記憶體失敗、服務異常或系統整體回應變慢甚至當機。",
                LikelyCauses = new[] { "某個程式有記憶體洩漏，用量持續增加不釋放", "實體記憶體不足、過度依賴分頁檔",
                    "同時執行過多服務或程式" },
                NextSteps = new[] { "用工作管理員/效能監視器找出記憶體用量異常增長的程序",
                    "重啟疑似洩漏的服務作為短期緩解", "評估是否需要增加實體記憶體",
                    "追查該程式是否有已知的記憶體洩漏問題並更新修補" } },

        // ── 服務 ────────────────────────────────────────────────
        new() { Id = "builtin-service-crash-loop-703x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7031, 7034 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "服務異常終止；反覆發生代表服務不穩定，需檢查應用程式錯誤",
                PlainExplanation = "某個 Windows 服務不正常地停止運作。",
                Impact = "偶發通常無害（服務會自動重啟）；反覆發生代表該服務本身或其依賴的程式不穩定，可能影響對應功能的可用性。",
                LikelyCauses = new[] { "服務程式本身有錯誤（未處理的例外）", "服務依賴的資源（資料庫、網路、檔案）暫時無法使用",
                    "資源不足（記憶體/CPU）導致服務被系統終止" },
                NextSteps = new[] { "查看該服務對應的應用程式日誌，找出真正的錯誤原因",
                    "確認服務依賴的資源（DB 連線、網路、憑證）是否正常",
                    "若反覆發生，考慮設定服務自動修復動作並持續觀察",
                    "必要時聯繫應用程式廠商或開發團隊排查" } },
        new() { Id = "builtin-service-start-failure-700x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7000, 7001 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium,
                Description = "服務啟動失敗",
                PlainExplanation = "某個 Windows 服務在啟動時失敗，沒有成功執行。",
                Impact = "該服務對應的功能將無法使用，若是關鍵服務（如資料庫、網路服務）會直接影響系統可用性。",
                LikelyCauses = new[] { "服務所需的相依服務未啟動或啟動失敗", "設定檔錯誤或遺失",
                    "服務帳戶權限不足或密碼過期", "執行檔或相依元件損毀/遺失" },
                NextSteps = new[] { "確認該服務的相依服務是否都已正常啟動", "檢查服務帳戶的密碼與權限是否有效",
                    "查看服務對應的詳細錯誤訊息與應用程式日誌", "嘗試手動啟動服務觀察即時錯誤" } },
        new() { Id = "builtin-security-new-service-7045", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Service Control Manager", EventIds = new[] { 7045 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "系統安裝了新服務——若非管理員預期的操作，可能是入侵者植入後門",
                PlainExplanation = "系統上被安裝了一個新的 Windows 服務。",
                Impact = "若非管理員預期的操作，這可能是入侵者植入的後門或惡意程式，一旦成立會讓攻擊者取得持續存取能力。",
                LikelyCauses = new[] { "合法的軟體安裝或系統更新（最常見情況）", "管理員手動安裝新服務進行維運",
                    "入侵者植入的持久化後門" },
                NextSteps = new[] { "確認是否為已知/預期的軟體安裝或維運操作",
                    "若無法確認來源，檢查該服務的執行檔路徑、簽章與建立時間",
                    "非預期時立即停用該服務並進一步鑑識調查",
                    "確認的合法安裝可標記為已知雜訊，供規則表未來調整參考" } },

        // ── 營運健康（備份、時間、憑證、網域設定）────────────────────
        new() { Id = "builtin-backup-failure-517", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Backup", EventIds = new[] { 517 },
                Category = IssueCategory.Backup, Severity = IssueSeverity.High,
                Description = "Windows Server Backup 備份失敗——備份損壞往往到需要還原時才發現，應立即檢查",
                PlainExplanation = "Windows Server Backup 的備份工作失敗了。",
                Impact = "備份失敗往往在真正需要還原資料時才會被發現，屆時可能已經沒有可用的備份可供救援。",
                LikelyCauses = new[] { "備份目標磁碟/位置空間不足或無法存取", "備份的來源磁碟區有錯誤（如磁碟/檔案系統問題）",
                    "備份服務或 VSS 元件異常", "備份排程與其他工作衝突" },
                NextSteps = new[] { "立即查看備份失敗的詳細錯誤訊息", "確認備份目的地（磁碟/網路共用）空間與連線正常",
                    "手動重跑一次備份確認是否可成功", "找出最近一次成功備份的時間點，評估目前的資料風險缺口" } },
        new() { Id = "builtin-backup-vss-error", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = true, MatchFilter = null,
                SourcePattern = "VSS",
                Category = IssueCategory.Backup, Severity = IssueSeverity.Medium,
                Description = "磁碟區陰影複製 (VSS) 錯誤，會導致備份失敗或不完整",
                PlainExplanation = "磁碟區陰影複製服務 (VSS) 發生錯誤，這是備份與還原點功能背後的關鍵元件。",
                Impact = "VSS 異常會導致備份失敗或不完整，也會影響還原點/快照功能無法正常使用。",
                LikelyCauses = new[] { "磁碟空間不足導致 VSS 儲存區無法配置", "VSS 相關服務未正常啟動",
                    "第三方應用程式的 VSS writer 異常", "磁碟本身有健康問題" },
                NextSteps = new[] { "用 vssadmin list writers 檢查是否有 writer 處於錯誤狀態",
                    "確認磁碟可用空間充足", "重啟 Volume Shadow Copy 相關服務", "確認後續備份工作是否恢復正常" } },
        new() { Id = "builtin-config-time-sync-failure", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Time-Service", EventIds = new[] { 29, 36, 47, 50 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "時間同步失敗；時鐘偏移超過 5 分鐘會導致 Kerberos 驗證與網域登入全面失敗",
                PlainExplanation = "系統與時間伺服器的時間同步失敗，伺服器時鐘可能開始偏移。",
                Impact = "時鐘偏移超過約 5 分鐘會導致 Kerberos 驗證失敗，使用者與服務可能突然無法登入或存取網域資源。",
                LikelyCauses = new[] { "無法連線到時間來源伺服器（網路問題或設定錯誤）", "時間伺服器本身異常",
                    "網域控制站的時間服務設定問題" },
                NextSteps = new[] { "確認可以連線到設定的時間來源（NTP server / 網域中的 PDC）",
                    "手動執行 w32tm /resync 測試同步", "檢查目前時鐘偏移量，若已偏移應盡快手動校正",
                    "確認網域時間架構設定正確（PDC Emulator 角色）" } },
        new() { Id = "builtin-config-cert-expiring-64", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "AutoEnrollment", EventIds = new[] { 64 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "憑證即將到期——過期會造成 TLS 或服務中斷，是最容易預防的停機原因之一",
                PlainExplanation = "系統上有一張憑證即將到期。",
                Impact = "憑證過期後，依賴它的 TLS 連線、服務驗證會失敗，可能造成無預警的服務中斷。",
                LikelyCauses = new[] { "憑證自動更新（AutoEnrollment）失敗或未設定", "憑證授權單位（CA）連線異常",
                    "手動核發的憑證到期前未安排更新" },
                NextSteps = new[] { "確認是哪張憑證即將到期（用途、使用它的服務）", "檢查自動註冊/更新是否正常運作",
                    "無法自動更新時安排手動更新流程", "更新完成後確認相關服務已載入新憑證" } },
        new() { Id = "builtin-config-schannel-36870", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Schannel", EventIds = new[] { 36870 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium,
                Description = "TLS 憑證私鑰存取失敗，常見於憑證過期或權限異常",
                PlainExplanation = "系統嘗試使用 TLS 憑證的私鑰時失敗，通常代表憑證有問題或存取權限異常。",
                Impact = "會導致使用該憑證的 TLS/SSL 連線（如 HTTPS、LDAPS）建立失敗，服務對外連線可能中斷。",
                LikelyCauses = new[] { "憑證已過期或已被撤銷", "私鑰檔案的存取權限被異動，服務帳戶無法讀取",
                    "憑證存放區異常" },
                NextSteps = new[] { "確認相關憑證是否已過期（對照憑證即將到期告警）",
                    "檢查該憑證私鑰的存取權限（ACL）是否正確", "必要時重新匯入或重新核發憑證",
                    "確認相關服務（如 IIS）在憑證更新後已重啟載入" } },
        new() { Id = "builtin-config-group-policy-failure", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "GroupPolicy", EventIds = new[] { 1030, 1058 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "群組原則套用失敗，可能為 SYSVOL 或網域控制站連線問題",
                PlainExplanation = "群組原則 (Group Policy) 套用失敗，代表主機無法正確取得網域管理的設定。",
                Impact = "持續失敗會讓伺服器逐漸偏離公司標準設定（安全性原則、軟體限制等），也可能是 SYSVOL 或網域連線更大問題的前兆。",
                LikelyCauses = new[] { "無法連線到網域控制站或 SYSVOL 共用資料夾", "DNS 解析網域控制站失敗",
                    "網路連線問題或防火牆阻擋", "群組原則物件本身設定錯誤" },
                NextSteps = new[] { "執行 gpupdate /force 並觀察詳細錯誤訊息",
                    "確認主機可以正常解析並連線到網域控制站", "檢查 SYSVOL 共用資料夾的存取權限",
                    "持續失敗應同步檢查該主機的網域信任關係是否正常" } },
        new() { Id = "builtin-config-netlogon-5719", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "NETLOGON", EventIds = new[] { 5719 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "無法連上網域控制站，網域驗證將受影響",
                PlainExplanation = "系統無法連線到網域控制站，這會影響網域登入與驗證功能。",
                Impact = "持續無法連線會導致使用網域帳號的登入失敗、群組原則無法套用，嚴重時整台伺服器形同脫離網域管理。",
                LikelyCauses = new[] { "網路連線中斷或不穩定", "DNS 設定錯誤，無法解析網域控制站",
                    "網域控制站本身故障或離線", "伺服器的電腦帳戶密碼與網域不同步" },
                NextSteps = new[] { "確認伺服器網路連線與 DNS 設定正常", "確認至少一台網域控制站可正常連線",
                    "檢查是否為網域控制站端的問題（其他伺服器是否也受影響）",
                    "持續發生時考慮用 netdom 重置電腦帳戶信任關係" } },
        new() { Id = "builtin-resource-dhcp-pool-low", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "DhcpServer", EventIds = new[] { 1020 },
                Category = IssueCategory.Resource, Severity = IssueSeverity.Medium,
                Description = "DHCP 位址池即將耗盡，新裝置將無法取得 IP（僅 DHCP 伺服器角色會出現）",
                PlainExplanation = "DHCP 伺服器可分配的 IP 位址即將用完。",
                Impact = "位址池耗盡後，新裝置連上網路將無法取得 IP，形同無法連網。",
                LikelyCauses = new[] { "位址池範圍設定原本就偏小", "租約時間過長，IP 未及時回收",
                    "網路上裝置數量成長超出原始規劃", "有裝置異常佔用大量 IP（如訪客網路濫用）" },
                NextSteps = new[] { "檢查目前位址池使用率與可用剩餘量", "評估是否可縮短租約時間加速回收",
                    "評估擴充位址池範圍（新增子網段或調整遮罩）", "排查是否有異常裝置佔用大量 IP" } },
        new() { Id = "builtin-service-app-crash-1000", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Application Error", EventIds = new[] { 1000 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = "應用程式反覆崩潰——服務完全掛掉之前通常先出現這個訊號",
                PlainExplanation = "某個應用程式反覆發生錯誤崩潰。",
                Impact = "反覆崩潰通常是服務即將完全無法使用的前兆，也可能造成資料未儲存或處理中斷。",
                LikelyCauses = new[] { "應用程式本身有臭蟲（未處理的例外）", "應用程式相依的元件或函式庫版本不相容",
                    "資源不足（記憶體/磁碟）導致執行異常", "資料損毀或輸入異常觸發程式錯誤" },
                NextSteps = new[] { "記錄崩潰的應用程式名稱、模組與錯誤代碼，查詢是否為已知問題",
                    "確認該應用程式與相依元件是否需要更新/修補", "檢查系統資源是否充足",
                    "若為自行開發的應用程式，將錯誤資訊回報開發團隊排查" } },
        new() { Id = "builtin-service-dotnet-exception-1026", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = ".NET Runtime", EventIds = new[] { 1026 },
                Category = IssueCategory.Service, Severity = IssueSeverity.Medium, CountThreshold = 3,
                Description = ".NET 應用程式未處理例外反覆發生",
                PlainExplanation = "某個 .NET 應用程式反覆發生未處理的程式錯誤。",
                Impact = "反覆發生代表該應用程式不穩定，可能導致功能中斷或資料處理錯誤，情況惡化可能造成服務完全停擺。",
                LikelyCauses = new[] { "程式邏輯錯誤（未處理的例外狀況）", ".NET Runtime 版本與應用程式不相容",
                    "應用程式相依的外部資源（資料庫、API）異常" },
                NextSteps = new[] { "查看完整例外堆疊，找出實際發生錯誤的程式模組",
                    "確認 .NET Runtime 版本是否符合應用程式需求",
                    "回報開發團隊修補，並評估是否需要暫時的因應措施（如自動重啟）" } },
        new() { Id = "builtin-config-windows-update-failure-20", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "WindowsUpdateClient", EventIds = new[] { 20 },
                Category = IssueCategory.Config, Severity = IssueSeverity.Low,
                Description = "Windows Update 安裝失敗，持續失敗累積未修補的安全風險",
                PlainExplanation = "Windows Update 的更新安裝失敗。",
                Impact = "單次失敗風險不高，但持續累積會讓系統長期缺乏安全性修補，增加被已知漏洞攻擊的風險。",
                LikelyCauses = new[] { "更新元件本身損毀，需要修復工具處理", "磁碟空間不足",
                    "與其他已安裝的軟體/更新衝突", "網路連線中斷導致下載失敗" },
                NextSteps = new[] { "查看具體失敗的更新項目與錯誤代碼", "確認磁碟空間是否充足",
                    "嘗試執行 Windows Update 疑難排解工具或手動安裝該更新",
                    "持續失敗應排入定期維護清單，避免長期未修補" } },

        // ── 安全 / 入侵跡象（Security log）──────────────────────────
        new() { Id = "builtin-security-bruteforce-4625", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4625 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High, CountThreshold = 10,
                Description = "登入失敗；短時間大量發生代表帳號密碼暴力破解攻擊",
                PlainExplanation = "短時間內出現大量登入失敗，這是帳號密碼暴力破解攻擊的典型特徵。",
                Impact = "若攻擊持續且密碼強度不足，攻擊者可能成功登入取得帳號的存取權限，進一步在系統內活動。",
                LikelyCauses = new[] { "外部或內部來源對特定帳號進行密碼猜測攻擊",
                    "自動化掃描工具對開放服務（如 RDP）進行帳密嘗試",
                    "合法使用者密碼設定錯誤持續重試（機率較低但需排除）" },
                NextSteps = new[] { "確認攻擊來源 IP 與被嘗試的帳號，評估是否需要封鎖來源",
                    "確認相關帳號密碼是否仍安全（未被猜中）——比對是否有同組帳號/IP 的成功登入",
                    "檢查該服務是否有必要對外開放，或加上多因素驗證/IP 白名單",
                    "考慮啟用帳戶鎖定原則降低暴力破解成功機率" } },
        new() { Id = "builtin-security-account-lockout-4740", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4740 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被鎖定，通常是暴力破解的結果",
                PlainExplanation = "有一個使用者帳戶因為連續登入失敗而被系統自動鎖定。",
                Impact = "通常是暴力破解攻擊的結果，也可能是使用者忘記密碼的正常情況——需要判讀是哪一種才能決定後續動作。",
                LikelyCauses = new[] { "暴力破解攻擊觸發帳戶鎖定原則", "使用者本人忘記密碼多次嘗試",
                    "應用程式或排程工作使用過期密碼持續重試" },
                NextSteps = new[] { "對照是否有同帳號的大量登入失敗（4625），確認是否為攻擊所致",
                    "聯繫帳戶擁有者確認是否為本人操作",
                    "若為攻擊，追查來源並考慮加強防護；若為誤鎖，依正常流程解鎖" } },
        new() { Id = "builtin-security-audit-log-cleared-1102", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 1102 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Critical,
                Description = "安全稽核日誌被清除——入侵者滅跡的典型行為，應立即調查",
                PlainExplanation = "伺服器的安全稽核日誌被清除了——這是攻擊者入侵後常見的滅跡行為。",
                Impact = "日誌被清除代表清除時間點之前的活動紀錄已經遺失，會嚴重影響後續的入侵調查與鑑識工作。",
                LikelyCauses = new[] { "入侵者取得管理權限後清除紀錄以掩蓋行蹤",
                    "管理員的正常維運操作（如日誌歸檔前清空）——需確認是否為預期行為", "自動化的日誌管理工具設定" },
                NextSteps = new[] { "立即確認是否為已知的管理操作（誰在什麼時候執行的）",
                    "若無法確認來源，視為入侵事件立即啟動調查程序",
                    "檢查該時間點前後是否有其他異常活動（其他主機的登入、權限異動等）",
                    "確認是否有其他日誌來源（如集中式 SIEM）保留了被清除前的紀錄" } },
        new() { Id = "builtin-security-audit-policy-changed-4719", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4719 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "稽核原則被變更，可能是入侵者關閉記錄以躲避偵測",
                PlainExplanation = "系統的安全稽核原則被變更了，這可能會讓某些活動不再被記錄。",
                Impact = "若被入侵者用來關閉特定稽核項目，後續的惡意活動將不會留下紀錄，等於製造了偵測死角。",
                LikelyCauses = new[] { "管理員調整稽核原則以符合合規或效能需求", "入侵者關閉稽核以躲避後續行為被記錄" },
                NextSteps = new[] { "確認變更是否為已知的管理操作",
                    "檢查變更後的稽核原則內容，確認關鍵項目（登入、帳戶管理等）是否仍在記錄",
                    "非預期變更時視為可疑，進一步調查操作來源" } },
        new() { Id = "builtin-security-account-created-472x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4720, 4722, 4724 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶建立/啟用/密碼被重設——若非預期操作可能為入侵者建立立足點",
                PlainExplanation = "有新的使用者帳戶被建立、被啟用，或有人的密碼被重設。",
                Impact = "若非預期操作，可能是入侵者建立自己的後門帳號，或竄改既有帳號密碼以取得存取權。",
                LikelyCauses = new[] { "IT 人員正常的帳號建立/管理作業", "入侵者建立新帳號作為立足點",
                    "入侵者重設既有帳號密碼以取得控制權" },
                NextSteps = new[] { "確認是否為已知的帳戶管理操作及執行者",
                    "非預期時立即檢查該帳號的權限範圍與近期活動",
                    "確認被重設密碼的帳戶本人是否知情，若非本人請求應視為可疑" } },
        new() { Id = "builtin-security-privileged-group-add-47xx", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4728, 4732, 4756 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被加入特權群組（如 Administrators），需確認是否為授權操作——典型提權手法",
                PlainExplanation = "有帳戶被加入了 Administrators 等特權群組，取得更高的系統權限。",
                Impact = "若非授權操作，代表攻擊者已完成權限提升，能對系統做幾乎任何事，風險等級極高。",
                LikelyCauses = new[] { "管理員授權的正常權限調整", "入侵者取得初始存取後進行權限提升的典型手法" },
                NextSteps = new[] { "立即確認是誰、為何將該帳戶加入特權群組",
                    "非預期時立即將該帳戶移出特權群組並鎖定調查",
                    "檢查該帳戶近期的其他活動，評估是否已造成損害" } },
        new() { Id = "builtin-security-privileged-group-remove-47xx", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4729, 4733, 4757 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "帳戶被移出特權群組，需確認是否為授權操作——也可能是入侵者提權得手後移除紀錄以滅跡",
                PlainExplanation = "有帳戶被移出了特權群組。",
                Impact = "多數情況是正常的權限回收；但也可能是入侵者提權得手後移除操作紀錄以滅跡，需要一併確認情境。",
                LikelyCauses = new[] { "管理員正常的權限回收作業（如人員離職、專案結束）",
                    "入侵者清除自己曾經被加入特權群組的痕跡" },
                NextSteps = new[] { "確認變更是否為已知的權限管理操作",
                    "對照是否同時有該帳戶先前被加入特權群組的紀錄，評估是否為滅跡行為",
                    "非預期時比照入侵事件調查" } },
        new() { Id = "builtin-security-persistence-service-task-469x", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4697, 4698 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "安裝服務或建立排程任務——攻擊者常見的持久化手法",
                PlainExplanation = "系統上有新服務被安裝，或有新的排程任務被建立。",
                Impact = "這是攻擊者常見的持久化手法——即使當下被發現，也能透過排程或服務在之後重新啟動惡意程式。",
                LikelyCauses = new[] { "合法的軟體安裝或維運排程設定", "入侵者植入的持久化機制" },
                NextSteps = new[] { "確認是否為已知的安裝或排程設定操作",
                    "檢查新服務/排程任務的執行內容、路徑與觸發時間是否合理",
                    "非預期時立即停用並進一步鑑識調查來源" } },

        // ── 權限與角色異動（無論授予或移除都要關注）──────────────────────
        new() { Id = "builtin-security-acl-changed-4670", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4670 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "檔案／資料夾／登錄物件的權限 (ACL) 被變更，需確認是否為授權操作",
                PlainExplanation = "檔案、資料夾或登錄機碼的存取權限 (ACL) 被變更。",
                Impact = "若被入侵者用來放寬敏感資源的存取權限，可能為後續竊取資料或持久化鋪路。",
                LikelyCauses = new[] { "管理員正常的權限調整作業", "入侵者調整權限以利後續存取或植入惡意程式" },
                NextSteps = new[] { "確認變更的物件是什麼、變更內容為何", "確認是否為已知的授權操作",
                    "非預期時檢查該物件目前的存取權限是否合理，並追查異動來源" } },
        new() { Id = "builtin-security-sacl-changed-4907", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4907 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Critical,
                Description = "物件的稽核設定 (SACL) 被變更——可能是入侵者針對特定物件關閉稽核記錄以躲避偵測",
                PlainExplanation = "某個物件的稽核設定被變更，可能導致該物件之後的存取行為不再被記錄。",
                Impact = "這是針對性關閉稽核的手法，代表攻擊者可能已鎖定特定敏感物件（檔案、機碼），意圖在該處活動而不留紀錄。",
                LikelyCauses = new[] { "管理員調整特定物件的稽核設定", "入侵者針對性關閉敏感物件的稽核追蹤" },
                NextSteps = new[] { "確認是哪個物件、變更了什麼稽核設定", "確認是否為已知操作",
                    "非預期時視為高度可疑，優先調查該物件近期的存取紀錄與相關帳戶活動" } },
        new() { Id = "builtin-security-user-rights-4717", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4717, 4718 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "系統存取權限被授予/移除（User Rights Assignment），需確認是否為授權操作",
                PlainExplanation = "使用者權限指派 (User Rights Assignment) 被變更，例如「以服務身分登入」等系統層級權限。",
                Impact = "這類權限直接影響帳戶能執行的系統層級操作，若被濫用可能繞過一般的存取控制。",
                LikelyCauses = new[] { "管理員設定服務帳戶或應用程式所需的系統權限",
                    "入侵者授予自己控制的帳戶額外的系統層級權限" },
                NextSteps = new[] { "確認變更內容（哪個權限、授予給誰）與操作者", "確認是否為已知的系統設定操作",
                    "非預期時檢查該帳戶目前擁有的完整權限範圍" } },
        new() { Id = "builtin-security-user-rights-assignment-4704", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4704, 4705 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "使用者權限指派被新增/移除，影響帳戶可執行的系統層級操作範圍",
                PlainExplanation = "帳戶被新增或移除了特定的使用者權限指派。",
                Impact = "影響帳戶可執行的系統層級操作範圍，若遭濫用可能讓一般帳戶取得原本不該有的能力。",
                LikelyCauses = new[] { "管理員的系統設定調整", "入侵者調整帳戶權限以利後續操作" },
                NextSteps = new[] { "確認變更內容與操作者是否為已知操作",
                    "非預期時檢查該帳戶目前完整權限並評估風險" } },
        new() { Id = "builtin-security-token-privilege-4703", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4703 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "權杖 (token) 特殊權限於執行期間被調整——常見的權限提升攻擊手法",
                PlainExplanation = "某個帳戶在執行期間被調整了權杖 (token) 上的特殊權限，這是常見的權限提升攻擊手法。",
                Impact = "攻擊者常利用此手法讓程式暫時取得超出帳戶原本範圍的權限，執行原本無法做到的操作。",
                LikelyCauses = new[] { "系統或應用程式的正常權限調整行為（部分合法程式運作機制）",
                    "入侵者利用漏洞或工具進行權限提升攻擊" },
                NextSteps = new[] { "確認觸發此事件的程式與帳戶是否為已知、可信的",
                    "非預期或來源不明時，視為可疑的權限提升嘗試進行調查",
                    "檢查該時間點前後是否有其他異常活動" } },
        new() { Id = "builtin-security-group-changed-4735", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4735 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "安全群組的內容或權限被變更",
                PlainExplanation = "某個安全群組的內容或權限設定被變更。",
                Impact = "若該群組具有重要權限，變更可能間接影響大量帳戶的存取範圍。",
                LikelyCauses = new[] { "管理員的正常群組管理作業", "入侵者變更群組設定以擴大自己或其他帳戶的存取權" },
                NextSteps = new[] { "確認是哪個群組、變更了什麼內容", "確認是否為已知操作",
                    "非預期時評估此群組成員的權限範圍與潛在影響" } },
        new() { Id = "builtin-security-domain-policy-changed-4739", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4739 },
                Category = IssueCategory.Security, Severity = IssueSeverity.High,
                Description = "網域原則被變更（僅網域控制站），影響範圍可能擴及整個網域",
                PlainExplanation = "網域等級的原則被變更了（僅網域控制站會出現），影響範圍可能涵蓋整個網域。",
                Impact = "網域原則變更影響所有加入該網域的電腦與使用者，若為惡意變更，波及範圍會遠大於單一主機事件。",
                LikelyCauses = new[] { "網域管理員的正常原則調整", "取得網域控制站權限的入侵者進行破壞性或提權變更" },
                NextSteps = new[] { "確認變更是否為已知的網域管理操作及執行者",
                    "非預期時視為高度嚴重事件，立即調查並考慮暫時還原原則",
                    "檢查是否有其他網域控制站也出現異常" } },
        new() { Id = "builtin-security-local-group-4731", Origin = "builtin", Enabled = true, Scope = "all", MatchAllEventIds = false, MatchFilter = null,
                SourcePattern = "Security-Auditing", EventIds = new[] { 4731, 4734 },
                Category = IssueCategory.Security, Severity = IssueSeverity.Medium,
                Description = "本機安全群組被建立/刪除，需確認是否為授權操作",
                PlainExplanation = "本機層級有安全群組被建立或刪除。",
                Impact = "本機群組通常影響範圍侷限於單一主機，但仍可能被用來規避既有的權限控管設計。",
                LikelyCauses = new[] { "管理員的本機帳戶管理作業", "入侵者建立群組作為權限管理或立足點的一部分" },
                NextSteps = new[] { "確認是否為已知的本機管理操作", "非預期時檢查該群組的成員與被賦予的權限" } },
    };
}
